FROM ccr.ccs.tencentyun.com/bk.io/centos7-cmdb:base
ENV container docker
COPY cmdb_adminserver /data/cmdb/cmdb_adminserver
RUN mkdir /data/cmdb/cmdb_adminserver/logs
RUN chmod +x /data/cmdb/cmdb_adminserver/cmdb_adminserver

