{{- if .Values.coreservice.enabled }}
apiVersion: {{ .Values.ApiVersion.Deployment }}
kind: Deployment
metadata:
  name: "{{ template "bk-cmdb.fullname" . }}-coreservice"
  labels:
    {{- include "bk-cmdb.labels" . | nindent 4 }}
    component: coreservice
spec:
  replicas: {{ .Values.coreservice.replicas }}
  selector:
    matchLabels:
      {{- include "bk-cmdb.matchLabels" . | nindent 6 }}
      component: coreservice
  template:
    metadata:
      labels:
        {{- include "bk-cmdb.labels" . | nindent 8 }}
        component: coreservice
      {{- with .Values.coreservice.annotations }}
      annotations:
        {{ toYaml . | indent 8 }}
      {{- end }}
      {{- if .Values.coreservice.podAnnotations }}
        {{ toYaml .Values.coreservice.podAnnotations | indent 8 }}
      {{- end }}
    spec:
      containers:
      - name: coreservice
        image: {{ .Values.coreservice.image.repository }}:{{ .Values.coreservice.image.tag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        workingDir: /data/bin/bk-cmdb/cmdb_coreservice/
        command: ["./cmdb_coreservice"]
        args:
        - --addrport=$(POD_IP):{{ .Values.coreservice.port }}
        - --regdiscv={{ .Release.Name }}-zookeeper:{{ .Values.zookeeper.service.ports.client.port }}
        {{- if .Values.coreservice.command.logDir }}
        - --log-dir
        - {{ .Values.coreservice.command.logDir }}
        {{- end }}
        {{- if .Values.coreservice.command.logLevel }}
        - --v
        - {{ .Values.coreservice.command.logLevel | quote }}
        {{- end -}}
        {{- if .Values.coreservice.command.logtostderr }}
        - --logtostderr
        - {{ .Values.coreservice.command.logtostderr }}
        {{- end }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.coreservice.port }}
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.coreservice.port }}
          initialDelaySeconds: 30
          periodSeconds: 10

        {{- if .Values.coreservice.resources }}
        resources:
          {{ toYaml .Values.coreservice.resources | indent 10 }}
        {{- end }}

        env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        {{- if .Values.coreservice.env -}}
          {{ toYaml .Values.coreservice.env | indent 10 }}
        {{- end }}

        ports:
        - containerPort: {{ .Values.coreservice.port }}

      {{- with .Values.coreservice.nodeSelector }}
      nodeSelector:
      {{ toYaml . | indent 8 }}
      {{- end }}

      {{- with .Values.coreservice.affinity }}
      affinity:
        {{ toYaml . | indent 8 }}
      {{- end }}

      {{- with .Values.coreservice.tolerations }}
      tolerations:
        {{ toYaml . | indent 8 }}
      {{- end }}

{{- end }}
