{{- if .Values.tmserver.enabled }}
apiVersion: {{ .Values.ApiVersion.Deployment }}
kind: Deployment
metadata:
  name: "{{ template "bk-cmdb.fullname" . }}-tmserver"
  labels:
    {{- include "bk-cmdb.labels" . | nindent 4 }}
    component: tmserver
spec:
  replicas: {{ .Values.tmserver.replicas }}
  selector:
    matchLabels:
      {{- include "bk-cmdb.matchLabels" . | nindent 6 }}
      component: tmserver
  template:
    metadata:
      labels:
        {{- include "bk-cmdb.labels" . | nindent 8 }}
        component: tmserver
      {{- with .Values.tmserver.annotations }}
      annotations:
        {{ toYaml . | indent 8 }}
      {{- end }}
      {{- if .Values.tmserver.podAnnotations }}
        {{ toYaml .Values.tmserver.podAnnotations | indent 8 }}
      {{- end }}
    spec:
      containers:
      - name: tmserver
        image: {{ .Values.tmserver.image.repository }}:{{ .Values.tmserver.image.tag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        workingDir: /data/bin/bk-cmdb/cmdb_tmserver/
        command: ["./cmdb_tmserver"]
        args:
        - --addrport=$(POD_IP):{{ .Values.tmserver.port }}
        - --regdiscv={{ .Release.Name }}-zookeeper:{{ .Values.zookeeper.service.ports.client.port }}
        {{- if .Values.tmserver.command.logDir }}
        - --log-dir
        - {{ .Values.tmserver.command.logDir }}
        {{- end }}
        {{- if .Values.tmserver.command.logLevel }}
        - --v
        - {{ .Values.tmserver.command.logLevel | quote }}
        {{- end }}
        {{- if .Values.tmserver.command.logtostderr }}
        - --logtostderr
        - {{ .Values.tmserver.command.logtostderr | quote }}
        {{- end }}

        {{- if .Values.tmserver.resources }}
        resources:
          {{ toYaml .Values.tmserver.resources | indent 10 }}
        {{- end }}

        env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        {{- if .Values.tmserver.env }}
          {{ toYaml .Values.tmserver.env | indent 10 }}
        {{- end }}

        ports:
        - containerPort: {{ .Values.tmserver.port }}

      {{- with .Values.tmserver.nodeSelector }}
      nodeSelector:
      {{ toYaml . | indent 8 }}
      {{- end }}

      {{- with .Values.tmserver.affinity }}
      affinity:
        {{ toYaml . | indent 8 }}
      {{- end }}

      {{- with .Values.tmserver.tolerations }}
      tolerations:
        {{ toYaml . | indent 8 }}
      {{- end }}

{{- end }}
