{{- if .Values.tmserver.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ template "bk-cmdb.tmserver" . }}"
  labels:
{{ include "bk-cmdb.labels" . | indent 4 }}
spec:
  ports:
    - port: 80
      targetPort: {{ .Values.tmserver.port }}
  selector:
{{ include "bk-cmdb.matchLabels" . | indent 4 }}
    component: tmserver
{{- end }}
