{{- if .Values.synchronizeserver.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ template "bk-cmdb.synchronizeserver" . }}"
  labels:
{{ include "bk-cmdb.labels" . | indent 4 }}
spec:
  ports:
    - port: 80
      targetPort: {{ .Values.synchronizeserver.port }}
  selector:
{{ include "bk-cmdb.matchLabels" . | indent 4 }}
    component: synchronizeserver
{{- end }}
