apiVersion: v1
kind: Service
metadata:
  name: cmdb-standalone
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
      nodePort: {{ .Values.service.nodePort }}
  selector:
    app: cmdb-standalone
