{{- if .Values.adminserver.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ template "bk-cmdb.adminserver" . }}"
  labels:
{{ include "common.labels.standard" . | indent 4 }}
spec:
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.adminserver.port }}
  selector:
{{ include "common.labels.matchLabels" . | indent 4 }}
    component: adminserver
{{- end }}
