FROM mirrors.tencent.com/tencentos/tencentos3-minimal
ENV container docker
COPY cmdb_adminserver /data/cmdb/cmdb_adminserver
RUN mkdir /data/cmdb/cmdb_adminserver/logs
RUN chmod +x /data/cmdb/cmdb_adminserver/cmdb_adminserver
#time zone setting
ENV TimeZone=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TimeZone /etc/localtime && echo $TimeZone > /etc/timezone

