{{- if .Values.webserver.ingress.enabled -}}
{{- $serviceName := include "bk-cmdb.webserver" . -}}
{{- $servicePort := .Values.webserver.service.externalPort -}}
apiVersion: {{ include "common.capabilities.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ template "bk-cmdb.webserver" . }}
  labels:
{{ include "common.labels.standard" . | indent 4 }}
  annotations:
    {{- range $key, $value := .Values.webserver.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
    - host: {{ .Values.webserver.ingress.host }}
      http:
        paths:
        - backend: {{ include "common.ingress.backend" (dict "serviceName" $serviceName "servicePort" $servicePort "context" $) | nindent 12 }}
          path: /
          {{- if eq "true" (include "common.ingress.supportsPathType" .) }}
          pathType: ImplementationSpecific
          {{- end }}
  {{- if .Values.webserver.ingress.tls }}
  tls:
{{ toYaml .Values.webserver.ingress.tls | indent 4 }}
  {{- end -}}
{{- end -}}
