{{- if .Values.webserver.ingress.enabled -}}
{{- $serviceName := include "bk-cmdb.webserver" . -}}
{{- $servicePort := .Values.webserver.service.externalPort -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "bk-cmdb.webserver" . }}
  labels:
{{ include "common.labels.standard" . | indent 4 }}
  annotations:
    {{- range $key, $value := .Values.webserver.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
    - host: {{ .Values.webserver.ingress.host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
  {{- if .Values.webserver.ingress.tls }}
  tls:
{{ toYaml .Values.webserver.ingress.tls | indent 4 }}
  {{- end -}}
{{- end -}}
