{{- if .Values.webserver.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ template "bk-cmdb.webserver" . }}"
  labels:
{{ include "common.labels.standard" . | indent 4 }}
spec:
  type: {{ .Values.webserver.service.type }}
  ports:
  {{- with .Values.webserver.service.ports }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
{{ include "common.labels.matchLabels" . | indent 4 }}
    component: webserver
{{- end }}
