FROM ccr.ccs.tencentyun.com/bk.io/centos7-cmdb:base
ENV container docker
COPY cmdb_synchronizeserver /data/cmdb/cmdb_synchronizeserver
RUN mkdir /data/cmdb/cmdb_synchronizeserver/logs
RUN chmod +x /data/cmdb/cmdb_synchronizeserver/cmdb_synchronizeserver

