{{- if .Values.toposerver.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ template "bk-cmdb.toposerver" . }}"
  labels:
{{ include "common.labels.standard" . | indent 4 }}
spec:
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.toposerver.port }}
  selector:
{{ include "common.labels.matchLabels" . | indent 4 }}
    component: toposerver
{{- end }}
