{{- if .Values.hostserver.enabled }}
apiVersion: {{ .Values.ApiVersion.Deployment }}
kind: Deployment
metadata:
  name: "{{ template "bk-cmdb.fullname" . }}-hostserver"
  labels:
    {{- include "bk-cmdb.labels" . | nindent 4 }}
    component: hostserver
spec:
  replicas: {{ .Values.hostserver.replicas }}
  selector:
    matchLabels:
      {{- include "bk-cmdb.matchLabels" . | nindent 6 }}
      component: hostserver
  template:
    metadata:
      labels:
        {{- include "bk-cmdb.labels" . | nindent 8 }}
        component: hostserver
      {{- with .Values.hostserver.annotations }}
      annotations:
        {{ toYaml . | indent 8 }}
      {{- end }}
      {{- if .Values.hostserver.podAnnotations }}
        {{ toYaml .Values.hostserver.podAnnotations | indent 8 }}
      {{- end }}
    spec:
      containers:
      - name: hostserver
        image: {{ .Values.hostserver.image.repository }}:{{ .Values.hostserver.image.tag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        workingDir: /data/bin/bk-cmdb/cmdb_hostserver/
        command: ["./cmdb_hostserver"]
        args:
        - --addrport=$(POD_IP):{{ .Values.hostserver.port }}
        - --regdiscv={{ .Release.Name }}-zookeeper:{{ .Values.zookeeper.service.ports.client.port }}
        {{- if .Values.hostserver.command.logDir }}
        - --log-dir
        - {{ .Values.hostserver.command.logDir }}
        {{- end }}
        {{- if .Values.hostserver.command.logLevel }}
        - --v
        - {{ .Values.hostserver.command.logLevel | quote }}
        {{- end -}}
        {{- if .Values.hostserver.command.logtostderr }}
        - --logtostderr
        - {{ .Values.hostserver.command.logtostderr }}
        {{- end }}
        - "--enable-auth"
        - {{ .Values.cmdb.auth.enable | quote }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.hostserver.port }}
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.hostserver.port }}
          initialDelaySeconds: 30
          periodSeconds: 10

        {{- if .Values.hostserver.resources }}
        resources:
          {{ toYaml .Values.hostserver.resources | indent 10 }}
        {{- end }}

        env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        {{- if .Values.hostserver.env -}}
          {{ toYaml .Values.hostserver.env | indent 10 }}
        {{- end }}

        ports:
        - containerPort: {{ .Values.hostserver.port }}

      {{- with .Values.hostserver.nodeSelector }}
      nodeSelector:
      {{ toYaml . | indent 8 }}
      {{- end }}

      {{- with .Values.hostserver.affinity }}
      affinity:
        {{ toYaml . | indent 8 }}
      {{- end }}

      {{- with .Values.hostserver.tolerations }}
      tolerations:
        {{ toYaml . | indent 8 }}
      {{- end }}

{{- end }}
