{{- if .Values.coreservice.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ template "bk-cmdb.coreservice" . }}"
  labels:
{{ include "bk-cmdb.labels" . | indent 4 }}
spec:
  ports:
    - port: 80
      targetPort: {{ .Values.coreservice.port }}
  selector:
{{ include "bk-cmdb.matchLabels" . | indent 4 }}
    component: coreservice
{{- end }}
