{{- if .Values.operationserver.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ template "bk-cmdb.operationserver" . }}"
  labels:
{{ include "bk-cmdb.labels" . | indent 4 }}
spec:
  ports:
    - port: 80
      targetPort: {{ .Values.operationserver.port }}
  selector:
{{ include "bk-cmdb.matchLabels" . | indent 4 }}
    component: operationserver
{{- end }}
