FROM mirrors.tencent.com/tencentos/tencentos4-minimal
ENV container docker
COPY cmdb_cacheservice /data/cmdb/cmdb_cacheservice
RUN mkdir /data/cmdb/cmdb_cacheservice/logs
RUN chmod +x /data/cmdb/cmdb_cacheservice/cmdb_cacheservice
#time zone setting
ENV TimeZone=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TimeZone /etc/localtime && echo $TimeZone > /etc/timezone