{{- if .Values.hostserver.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ template "bk-cmdb.hostserver" . }}"
  labels:
{{ include "bk-cmdb.labels" . | indent 4 }}
spec:
  ports:
    - port: 80
      targetPort: {{ .Values.hostserver.port }}
  selector:
{{ include "bk-cmdb.matchLabels" . | indent 4 }}
    component: hostserver
{{- end }}
