FROM ccr.ccs.tencentyun.com/bk.io/centos7-cmdb:base
ENV container docker
COPY cmdb_procserver /data/cmdb/cmdb_procserver
RUN mkdir /data/cmdb/cmdb_procserver/logs
RUN chmod +x /data/cmdb/cmdb_procserver/cmdb_procserver
#time zone setting
ENV TimeZone=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TimeZone /etc/localtime && echo $TimeZone > /etc/timezone

