{
 "title": "gse-data",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "基础数据",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "总数据流量",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "display": "false",
       "expression": "a",
       "query_configs": [
        {
         "alias": "接收送数据量",
         "data_source_label": "bk_monitor",
         "data_type_label": "time_series",
         "display": "true",
         "filter_dict": {},
         "functions": [
          {
           "id": "rate",
           "params": [
            { "id": "window", "value": "2m" }
           ]
          }
         ],
         "group_by": [],
         "interval": 60,
         "interval_unit": "s",
         "method": "SUM",
         "metric_field": "data_total_recv_msg_bytets",
         "refId": "a",
         "result_table_id": "",
         "result_table_label": "kubernetes",
         "time_field": "",
         "where": [
          { "key": "module", "method": "eq", "value": [ "data" ] }
         ]
        }
       ]
      },
      {
       "display": "false",
       "expression": "a",
       "query_configs": [
        {
         "alias": "发送数据量",
         "data_source_label": "bk_monitor",
         "data_type_label": "time_series",
         "display": "true",
         "filter_dict": {},
         "functions": [
          {
           "id": "rate",
           "params": [
            { "id": "window", "value": "2m" }
           ]
          }
         ],
         "group_by": [],
         "interval": 60,
         "interval_unit": "s",
         "method": "SUM",
         "metric_field": "data_total_send_msg_bytets",
         "refId": "a",
         "result_table_id": "",
         "result_table_label": "kubernetes",
         "time_field": "",
         "where": [
          { "key": "module", "method": "eq", "value": [ "data" ] }
         ]
        }
       ]
      }
     ]
    },
    {
     "title": "TCP连接数",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expression": "a",
       "query_configs": [
        {
         "alias": "$tag_bk_pod",
         "data_source_label": "bk_monitor",
         "data_type_label": "time_series",
         "display": "true",
         "filter_dict": {},
         "functions": [],
         "group_by": [ "bk_pod" ],
         "interval": 60,
         "interval_unit": "s",
         "method": "SUM",
         "metric_field": "process_connection_count",
         "refId": "a",
         "result_table_id": "",
         "result_table_label": "kubernetes",
         "time_field": "",
         "where": [
          { "key": "module", "method": "eq", "value": [ "data" ] }
         ]
        }
       ]
      }
     ]
    },
    {
     "title": "ChannelID数量",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "display": "false",
       "expression": "a",
       "query_configs": [
        {
         "alias": "$tag_bk_pod",
         "data_source_label": "bk_monitor",
         "data_type_label": "time_series",
         "display": true,
         "filter_dict": {},
         "functions": [],
         "group_by": [ "bk_pod" ],
         "interval": 60,
         "interval_unit": "s",
         "method": "AVG",
         "metric_field": "channel_id_count",
         "refId": "a",
         "result_table_id": "",
         "result_table_label": "kubernetes",
         "time_field": "",
         "where": [
          { "key": "module", "method": "eq", "value": [ "data" ] }
         ]
        }
       ]
      }
     ]
    },
    {
     "title": "ChannelID内存使用量",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "deckbytes" }
     ],
     "targets": [
      {
       "display": "false",
       "expression": "a",
       "query_configs": [
        {
         "alias": "$tag_bk_pod",
         "data_source_label": "bk_monitor",
         "data_type_label": "time_series",
         "display": "true",
         "filter_dict": {},
         "functions": [],
         "group_by": [ "bk_pod" ],
         "interval": 60,
         "interval_unit": "s",
         "method": "AVG",
         "metric_field": "channel_id_memusage",
         "refId": "a",
         "result_table_id": "",
         "result_table_label": "kubernetes",
         "time_field": "",
         "where": [
          { "key": "module", "method": "eq", "value": [ "data" ] }
         ]
        }
       ]
      }
     ]
    },
    {
     "title": "内部队列待处理消息量",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "display": "false",
       "expression": "a",
       "query_configs": [
        {
         "alias": "$tag_bk_pod",
         "data_source_label": "bk_monitor",
         "data_type_label": "time_series",
         "display": "true",
         "filter_dict": {},
         "functions": [
          {
           "id": "rate",
           "params": [
            { "id": "window", "value": "2m" }
           ]
          }
         ],
         "group_by": [ "bk_pod" ],
         "interval": 60,
         "interval_unit": "s",
         "method": "SUM",
         "metric_field": "worker_queune_msg_count",
         "refId": "a",
         "result_table_id": "",
         "result_table_label": "kubernetes",
         "time_field": "",
         "where": [
          { "key": "module", "method": "eq", "value": [ "data" ] }
         ]
        }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "接收数据",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "TCP消息数",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "query_configs": [
        {
         "alias": "$tag_bk_pod",
         "data_source_label": "bk_monitor",
         "data_type_label": "time_series",
         "display": true,
         "filter_dict": {},
         "functions": [
          {
           "id": "rate",
           "params": [
            { "id": "window", "value": "1m" }
           ]
          }
         ],
         "group_by": [ "bk_pod" ],
         "interval": 30,
         "interval_unit": "s",
         "method": "SUM",
         "metric_field": "recv_msg_counter",
         "refId": "a",
         "result_table_id": "",
         "result_table_label": "kubernetes",
         "time_field": "",
         "where": [
          { "key": "module", "method": "eq", "value": [ "data" ] }
         ]
        }
       ]
      }
     ]
    },
    {
     "title": "TCP数据处理成功率",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_bk_pod",
       "expression": "a / b * 100",
       "query_configs": [
        {
         "alias": "",
         "data_source_label": "bk_monitor",
         "data_type_label": "time_series",
         "display": false,
         "filter_dict": {},
         "functions": [
          {
           "id": "rate",
           "params": [
            { "id": "window", "value": "2m" }
           ]
          }
         ],
         "group_by": [ "bk_pod" ],
         "interval": 30,
         "interval_unit": "s",
         "method": "SUM",
         "metric_field": "recv_msg_counter",
         "refId": "a",
         "result_table_id": "",
         "result_table_label": "kubernetes",
         "time_field": "",
         "where": [
          { "key": "error", "method": "eq", "value": [ "0" ] }
         ]
        },
        {
         "alias": "",
         "data_source_label": "bk_monitor",
         "data_type_label": "time_series",
         "display": false,
         "filter_dict": {},
         "functions": [
          {
           "id": "rate",
           "params": [
            { "id": "window", "value": "2m" }
           ]
          }
         ],
         "group_by": [ "bk_pod" ],
         "interval": "auto",
         "interval_unit": "s",
         "method": "SUM",
         "metric_field": "recv_msg_counter",
         "refId": "b",
         "result_table_id": "",
         "result_table_label": "kubernetes",
         "time_field": "",
         "where": []
        }
       ]
      }
     ]
    },
    {
     "title": "Agent动态数据协议消息统计",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "query_configs": [
        {
         "alias": "$tag_bk_pod",
         "data_source_label": "bk_monitor",
         "data_type_label": "time_series",
         "display": true,
         "filter_dict": {},
         "functions": [
          {
           "id": "rate",
           "params": [
            { "id": "window", "value": "1m" }
           ]
          }
         ],
         "group_by": [ "bk_pod" ],
         "interval": 60,
         "interval_unit": "s",
         "method": "SUM",
         "metric_field": "recv_msg_counter",
         "refId": "a",
         "result_table_id": "",
         "result_table_label": "kubernetes",
         "time_field": "",
         "where": [
          { "key": "codec", "method": "eq", "value": [ "codecv1" ] },
          { "condition": "and", "key": "message_type", "method": "eq", "value": [ "9" ] }
         ]
        }
       ]
      }
     ]
    },
    {
     "title": "非动态数据协议",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "query_configs": [
        {
         "alias": "$tag_bk_pod",
         "data_source_label": "bk_monitor",
         "data_type_label": "time_series",
         "display": true,
         "filter_dict": {},
         "functions": [
          {
           "id": "rate",
           "params": [
            { "id": "window", "value": "2m" }
           ]
          }
         ],
         "group_by": [ "bk_pod" ],
         "interval": 30,
         "interval_unit": "s",
         "method": "SUM",
         "metric_field": "recv_msg_counter",
         "refId": "a",
         "result_table_id": "",
         "result_table_label": "kubernetes",
         "time_field": "",
         "where": [
          { "key": "codec", "method": "eq", "value": [ "codecv1" ] },
          { "condition": "and", "key": "message_type", "method": "eq", "value": [ "3084" ] }
         ]
        }
       ]
      }
     ]
    },
    {
     "title": "Agent心跳消息",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "query_configs": [
        {
         "alias": "$tag_bk_pod",
         "data_source_label": "bk_monitor",
         "data_type_label": "time_series",
         "display": true,
         "filter_dict": {},
         "functions": [
          {
           "id": "rate",
           "params": [
            { "id": "window", "value": "2m" }
           ]
          }
         ],
         "group_by": [ "bk_pod" ],
         "interval": 60,
         "interval_unit": "s",
         "method": "SUM",
         "metric_field": "recv_msg_counter",
         "refId": "a",
         "result_table_id": "",
         "result_table_label": "kubernetes",
         "time_field": "",
         "where": [
          { "key": "codec", "method": "eq", "value": [ "codecv1" ] },
          { "condition": "and", "key": "message_type", "method": "eq", "value": [ "1" ] }
         ]
        }
       ]
      }
     ]
    },
    {
     "title": "Agent2.0 接入调度",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "display": "false",
       "expression": "a",
       "query_configs": [
        {
         "alias": "$tag_bk_pod ($tag_apiname)",
         "data_source_label": "bk_monitor",
         "data_type_label": "time_series",
         "display": "true",
         "filter_dict": {},
         "functions": [
          {
           "id": "rate",
           "params": [
            { "id": "window", "value": "2m" }
           ]
          }
         ],
         "group_by": [
          "code",
          "apiname",
          "bk_pod"
         ],
         "interval": 60,
         "interval_unit": "s",
         "method": "SUM",
         "metric_field": "request_msg_count",
         "refId": "a",
         "result_table_id": "",
         "result_table_label": "kubernetes",
         "time_field": "",
         "where": [
          { "key": "module", "method": "eq", "value": [ "data" ] }
         ]
        }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "发送数据",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "kafka队列发送消息统计",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "query_configs": [
        {
         "alias": "$tag_bk_pod (success)",
         "data_source_label": "bk_monitor",
         "data_type_label": "time_series",
         "display": true,
         "filter_dict": {},
         "functions": [
          {
           "id": "rate",
           "params": [
            { "id": "window", "value": "2m" }
           ]
          }
         ],
         "group_by": [ "bk_pod" ],
         "interval": 60,
         "interval_unit": "s",
         "method": "SUM",
         "metric_field": "message_queue_request_counter",
         "refId": "a",
         "result_table_id": "",
         "result_table_label": "kubernetes",
         "time_field": "",
         "where": [
          { "key": "error_code", "method": "eq", "value": [ "0" ] },
          { "condition": "and", "key": "quene_type", "method": "eq", "value": [ "kafka" ] }
         ]
        }
       ]
      },
      {
       "query_configs": [
        {
         "alias": "$tag_bk_pod (failed)",
         "data_source_label": "bk_monitor",
         "data_type_label": "time_series",
         "display": true,
         "filter_dict": {},
         "functions": [
          {
           "id": "rate",
           "params": [
            { "id": "window", "value": "2m" }
           ]
          }
         ],
         "group_by": [ "bk_pod" ],
         "interval": 60,
         "interval_unit": "s",
         "method": "SUM",
         "metric_field": "message_queue_request_counter",
         "refId": "a",
         "result_table_id": "",
         "result_table_label": "kubernetes",
         "time_field": "",
         "where": [
          { "key": "quene_type", "method": "eq", "value": [ "kafka" ] },
          { "condition": "and", "key": "error_code", "method": "neq", "value": [ "0" ] }
         ]
        }
       ]
      }
     ]
    },
    {
     "title": "kafka队列发送消息成功率",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_bk_pod",
       "expression": "a /b * 100",
       "query_configs": [
        {
         "alias": "",
         "data_source_label": "bk_monitor",
         "data_type_label": "time_series",
         "display": false,
         "filter_dict": {},
         "functions": [],
         "group_by": [ "bk_pod" ],
         "interval": 60,
         "interval_unit": "s",
         "method": "SUM",
         "metric_field": "message_queue_request_counter",
         "refId": "a",
         "result_table_id": "",
         "result_table_label": "kubernetes",
         "time_field": "",
         "where": [
          { "key": "quene_type", "method": "eq", "value": [ "kafka" ] },
          { "condition": "and", "key": "error_code", "method": "eq", "value": [ "0" ] }
         ]
        },
        {
         "alias": "",
         "data_source_label": "bk_monitor",
         "data_type_label": "time_series",
         "display": false,
         "filter_dict": {},
         "functions": [],
         "group_by": [ "bk_pod" ],
         "interval": "auto",
         "interval_unit": "s",
         "method": "SUM",
         "metric_field": "message_queue_request_counter",
         "refId": "b",
         "result_table_id": "",
         "result_table_label": "kubernetes",
         "time_field": "",
         "where": [
          { "key": "quene_type", "method": "eq", "value": [ "kafka" ] }
         ]
        }
       ]
      }
     ]
    },
    {
     "title": "kafka耗时统计",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_bk_pod ($tag_quene_type)",
       "expression": "a / b",
       "query_configs": [
        {
         "alias": "$tag_bk_pod:$tag_quene_type",
         "data_source_label": "bk_monitor",
         "data_type_label": "time_series",
         "display": false,
         "filter_dict": {},
         "functions": [
          {
           "id": "rate",
           "params": [
            { "id": "window", "value": "1m" }
           ]
          }
         ],
         "group_by": [
          "bk_pod",
          "quene_type"
         ],
         "interval": 30,
         "interval_unit": "s",
         "method": "SUM",
         "metric_field": "message_queue_request_millseconds",
         "refId": "a",
         "result_table_id": "",
         "result_table_label": "kubernetes",
         "time_field": "",
         "where": [
          { "key": "module", "method": "eq", "value": [ "data" ] },
          { "condition": "and", "key": "quene_type", "method": "eq", "value": [ "kafka" ] }
         ]
        },
        {
         "alias": "$tag_bk_pod:$tag_quene_type",
         "data_source_label": "bk_monitor",
         "data_type_label": "time_series",
         "display": false,
         "filter_dict": {},
         "functions": [
          {
           "id": "rate",
           "params": [
            { "id": "window", "value": "1m" }
           ]
          }
         ],
         "group_by": [
          "bk_pod",
          "quene_type"
         ],
         "interval": 30,
         "interval_unit": "s",
         "method": "SUM",
         "metric_field": "message_queue_request_counter",
         "refId": "b",
         "result_table_id": "",
         "result_table_label": "kubernetes",
         "time_field": "",
         "where": [
          { "key": "module", "method": "eq", "value": [ "data" ] }
         ]
        }
       ]
      }
     ]
    },
    {
     "title": "redis队列发送消息统计",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "query_configs": [
        {
         "alias": "$tag_bk_pod (success)",
         "data_source_label": "bk_monitor",
         "data_type_label": "time_series",
         "display": true,
         "filter_dict": {},
         "functions": [
          {
           "id": "rate",
           "params": [
            { "id": "window", "value": "2m" }
           ]
          }
         ],
         "group_by": [ "bk_pod" ],
         "interval": 60,
         "interval_unit": "s",
         "method": "SUM",
         "metric_field": "message_queue_request_counter",
         "refId": "a",
         "result_table_id": "",
         "result_table_label": "kubernetes",
         "time_field": "",
         "where": [
          { "key": "direction", "method": "eq", "value": [ "request" ] },
          { "condition": "and", "key": "error_code", "method": "eq", "value": [ "0" ] },
          { "condition": "and", "key": "quene_type", "method": "eq", "value": [ "redis" ] }
         ]
        }
       ]
      },
      {
       "query_configs": [
        {
         "alias": "$tag_bk_pod (failed)",
         "data_source_label": "bk_monitor",
         "data_type_label": "time_series",
         "display": true,
         "filter_dict": {},
         "functions": [
          {
           "id": "rate",
           "params": [
            { "id": "window", "value": "2m" }
           ]
          }
         ],
         "group_by": [ "bk_pod" ],
         "interval": 60,
         "interval_unit": "s",
         "method": "SUM",
         "metric_field": "message_queue_request_counter",
         "refId": "a",
         "result_table_id": "",
         "result_table_label": "kubernetes",
         "time_field": "",
         "where": [
          { "key": "direction", "method": "eq", "value": [ "request" ] },
          { "condition": "and", "key": "error_code", "method": "neq", "value": [ "0" ] },
          { "condition": "and", "key": "quene_type", "method": "eq", "value": [ "redis" ] },
          { "condition": "and", "key": "module", "method": "eq", "value": [ "data" ] }
         ]
        }
       ]
      }
     ]
    },
    {
     "title": "redis队列发送消息成功率",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_bk_pod",
       "expression": "a /b * 100",
       "query_configs": [
        {
         "alias": "",
         "data_source_label": "bk_monitor",
         "data_type_label": "time_series",
         "display": false,
         "filter_dict": {},
         "functions": [],
         "group_by": [ "bk_pod" ],
         "interval": 30,
         "interval_unit": "s",
         "method": "SUM",
         "metric_field": "message_queue_request_counter",
         "refId": "a",
         "result_table_id": "",
         "result_table_label": "kubernetes",
         "time_field": "",
         "where": [
          { "key": "quene_type", "method": "eq", "value": [ "redis" ] },
          { "condition": "and", "key": "error_code", "method": "eq", "value": [ "0" ] }
         ]
        },
        {
         "alias": "",
         "data_source_label": "bk_monitor",
         "data_type_label": "time_series",
         "display": false,
         "filter_dict": {},
         "functions": [],
         "group_by": [ "bk_pod" ],
         "interval": 30,
         "interval_unit": "s",
         "method": "SUM",
         "metric_field": "message_queue_request_counter",
         "refId": "b",
         "result_table_id": "",
         "result_table_label": "kubernetes",
         "time_field": "",
         "where": [
          { "key": "quene_type", "method": "eq", "value": [ "redis" ] }
         ]
        }
       ]
      }
     ]
    },
    {
     "title": "redis耗时统计",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_bk_pod ($tag_quene_type)",
       "expression": "a / b",
       "query_configs": [
        {
         "alias": "$tag_bk_pod:$tag_quene_type",
         "data_source_label": "bk_monitor",
         "data_type_label": "time_series",
         "display": false,
         "filter_dict": {},
         "functions": [
          {
           "id": "rate",
           "params": [
            { "id": "window", "value": "1m" }
           ]
          }
         ],
         "group_by": [
          "bk_pod",
          "quene_type"
         ],
         "interval": 30,
         "interval_unit": "s",
         "method": "SUM",
         "metric_field": "message_queue_request_millseconds",
         "refId": "a",
         "result_table_id": "",
         "result_table_label": "kubernetes",
         "time_field": "",
         "where": [
          { "key": "module", "method": "eq", "value": [ "data" ] },
          { "condition": "and", "key": "quene_type", "method": "eq", "value": [ "redis" ] }
         ]
        },
        {
         "alias": "$tag_bk_pod:$tag_quene_type",
         "data_source_label": "bk_monitor",
         "data_type_label": "time_series",
         "display": false,
         "filter_dict": {},
         "functions": [
          {
           "id": "rate",
           "params": [
            { "id": "window", "value": "1m" }
           ]
          }
         ],
         "group_by": [
          "bk_pod",
          "quene_type"
         ],
         "interval": 30,
         "interval_unit": "s",
         "method": "SUM",
         "metric_field": "message_queue_request_counter",
         "refId": "b",
         "result_table_id": "",
         "result_table_label": "kubernetes",
         "time_field": "",
         "where": [
          { "key": "module", "method": "eq", "value": [ "data" ] }
         ]
        }
       ]
      }
     ]
    },
    {
     "title": "pulsar队列发送消息统计",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "query_configs": [
        {
         "alias": "$tag_bk_pod:failed",
         "data_source_label": "bk_monitor",
         "data_type_label": "time_series",
         "display": true,
         "filter_dict": {},
         "functions": [
          {
           "id": "rate",
           "params": [
            { "id": "window", "value": "2m" }
           ]
          }
         ],
         "group_by": [ "bk_pod" ],
         "interval": 60,
         "interval_unit": "s",
         "method": "SUM",
         "metric_field": "message_queue_request_counter",
         "refId": "a",
         "result_table_id": "",
         "result_table_label": "kubernetes",
         "time_field": "",
         "where": [
          { "key": "direction", "method": "eq", "value": [ "response" ] },
          { "condition": "and", "key": "error_code", "method": "neq", "value": [ "0" ] },
          { "condition": "and", "key": "quene_type", "method": "eq", "value": [ "pulasr" ] }
         ]
        }
       ]
      },
      {
       "query_configs": [
        {
         "alias": "$tag_bk_pod:success",
         "data_source_label": "bk_monitor",
         "data_type_label": "time_series",
         "display": true,
         "filter_dict": {},
         "functions": [
          {
           "id": "rate",
           "params": [
            { "id": "window", "value": "2m" }
           ]
          }
         ],
         "group_by": [ "bk_pod" ],
         "interval": 60,
         "interval_unit": "s",
         "method": "SUM",
         "metric_field": "message_queue_request_counter",
         "refId": "a",
         "result_table_id": "",
         "result_table_label": "kubernetes",
         "time_field": "",
         "where": [
          { "key": "direction", "method": "eq", "value": [ "response" ] },
          { "condition": "and", "key": "error_code", "method": "eq", "value": [ "0" ] },
          { "condition": "and", "key": "quene_type", "method": "eq", "value": [ "pulasr" ] }
         ]
        }
       ]
      }
     ]
    },
    {
     "title": "pulsar队列发送消息成功率",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "成功率",
       "expression": "a /b * 100",
       "query_configs": [
        {
         "alias": "",
         "data_source_label": "bk_monitor",
         "data_type_label": "time_series",
         "display": false,
         "filter_dict": {},
         "functions": [],
         "group_by": [ "bk_pod" ],
         "interval": 30,
         "interval_unit": "s",
         "method": "SUM",
         "metric_field": "message_queue_request_counter",
         "refId": "a",
         "result_table_id": "",
         "result_table_label": "kubernetes",
         "time_field": "",
         "where": [
          { "key": "quene_type", "method": "eq", "value": [ "pulsar" ] },
          { "condition": "and", "key": "error_code", "method": "eq", "value": [ "0" ] }
         ]
        },
        {
         "alias": "",
         "data_source_label": "bk_monitor",
         "data_type_label": "time_series",
         "display": false,
         "filter_dict": {},
         "functions": [],
         "group_by": [ "bk_pod" ],
         "interval": 30,
         "interval_unit": "s",
         "method": "SUM",
         "metric_field": "message_queue_request_counter",
         "refId": "b",
         "result_table_id": "",
         "result_table_label": "kubernetes",
         "time_field": "",
         "where": [
          { "key": "quene_type", "method": "eq", "value": [ "pulsar" ] }
         ]
        }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Channel API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "ChannelId API 成功率",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_apiname成功率($tag_bk_pod)",
       "expression": "a / b *100",
       "query_configs": [
        {
         "alias": "api-$tag_apiname($tag_node)",
         "data_source_label": "bk_monitor",
         "data_type_label": "time_series",
         "display": false,
         "filter_dict": {},
         "functions": [
          {
           "id": "rate",
           "params": [
            { "id": "window", "value": "2m" }
           ]
          }
         ],
         "group_by": [
          "apiname",
          "bk_pod"
         ],
         "interval": 120,
         "interval_unit": "s",
         "method": "SUM",
         "metric_field": "api_requests_total",
         "refId": "a",
         "result_table_id": "",
         "result_table_label": "kubernetes",
         "time_field": "",
         "where": [
          { "key": "code", "method": "eq", "value": [ "0" ] },
          { "condition": "and", "key": "module", "method": "eq", "value": [ "data" ] }
         ]
        },
        {
         "alias": "",
         "data_source_label": "bk_monitor",
         "data_type_label": "time_series",
         "display": false,
         "filter_dict": {},
         "functions": [
          {
           "id": "rate",
           "params": [
            { "id": "window", "value": "2m" }
           ]
          }
         ],
         "group_by": [
          "apiname",
          "bk_pod"
         ],
         "interval": 120,
         "interval_unit": "s",
         "method": "SUM",
         "metric_field": "api_requests_total",
         "refId": "b",
         "result_table_id": "",
         "result_table_label": "kubernetes",
         "time_field": "",
         "where": []
        }
       ]
      }
     ]
    },
    {
     "title": "ChannelId API耗时",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_apiname耗时($tag_bk_pod)",
       "expression": "a / b",
       "query_configs": [
        {
         "alias": "api-$tag_apiname($tag_node)",
         "data_source_label": "bk_monitor",
         "data_type_label": "time_series",
         "display": false,
         "filter_dict": {},
         "functions": [
          {
           "id": "rate",
           "params": [
            { "id": "window", "value": "1m" }
           ]
          }
         ],
         "group_by": [
          "apiname",
          "bk_pod"
         ],
         "interval": 60,
         "interval_unit": "s",
         "method": "SUM",
         "metric_field": "response_milliseconds",
         "refId": "a",
         "result_table_id": "",
         "result_table_label": "kubernetes",
         "time_field": "",
         "where": [
          { "key": "module", "method": "eq", "value": [ "data" ] }
         ]
        },
        {
         "alias": "",
         "data_source_label": "bk_monitor",
         "data_type_label": "time_series",
         "display": false,
         "filter_dict": {},
         "functions": [
          {
           "id": "rate",
           "params": [
            { "id": "window", "value": "1m" }
           ]
          }
         ],
         "group_by": [
          "apiname",
          "bk_pod"
         ],
         "interval": 60,
         "interval_unit": "s",
         "method": "SUM",
         "metric_field": "api_requests_total",
         "refId": "b",
         "result_table_id": "",
         "result_table_label": "kubernetes",
         "time_field": "",
         "where": [
          { "key": "module", "method": "eq", "value": [ "data" ] }
         ]
        }
       ]
      }
     ]
    },
    {
     "title": "ChannelId-API调用频率",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "query_configs": [
        {
         "alias": "api-$tag_apiname($tag_bk_pod)",
         "data_source_label": "bk_monitor",
         "data_type_label": "time_series",
         "display": true,
         "filter_dict": {},
         "functions": [
          {
           "id": "rate",
           "params": [
            { "id": "window", "value": "2m" }
           ]
          }
         ],
         "group_by": [
          "apiname",
          "bk_pod"
         ],
         "interval": 60,
         "interval_unit": "s",
         "method": "SUM",
         "metric_field": "api_requests_total",
         "refId": "a",
         "result_table_id": "",
         "result_table_label": "kubernetes",
         "time_field": "",
         "where": [
          { "key": "module", "method": "eq", "value": [ "data" ] }
         ]
        }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "系统性能指标",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "内存使用率",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "display": "false",
       "expression": "a",
       "query_configs": [
        {
         "alias": "$tag_bk_pod",
         "data_source_label": "bk_monitor",
         "data_type_label": "time_series",
         "display": "true",
         "filter_dict": {},
         "functions": [],
         "group_by": [ "bk_pod" ],
         "interval": 60,
         "interval_unit": "s",
         "method": "AVG",
         "metric_field": "process_mem_usage",
         "refId": "a",
         "result_table_id": "",
         "result_table_label": "kubernetes",
         "time_field": "",
         "where": [
          { "key": "module", "method": "eq", "value": [ "data" ] }
         ]
        }
       ]
      }
     ]
    },
    {
     "title": "线程数",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "display": "false",
       "expression": "a",
       "query_configs": [
        {
         "alias": "$tag_bk_pod",
         "data_source_label": "bk_monitor",
         "data_type_label": "time_series",
         "display": "true",
         "filter_dict": {},
         "functions": [],
         "group_by": [ "bk_pod" ],
         "interval": 60,
         "interval_unit": "s",
         "method": "AVG",
         "metric_field": "process_thread_total",
         "refId": "a",
         "result_table_id": "",
         "result_table_label": "kubernetes",
         "time_field": "",
         "where": [
          { "key": "module", "method": "eq", "value": [ "data" ] }
         ]
        }
       ]
      }
     ]
    },
    {
     "title": "CPU使用率",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "display": "false",
       "expression": "a",
       "query_configs": [
        {
         "alias": "$tag_bk_pod",
         "data_source_label": "bk_monitor",
         "data_type_label": "time_series",
         "display": "true",
         "filter_dict": {},
         "functions": [],
         "group_by": [ "bk_pod" ],
         "interval": 60,
         "interval_unit": "s",
         "method": "AVG",
         "metric_field": "process_cpu_usage_ratio",
         "refId": "a",
         "result_table_id": "",
         "result_table_label": "kubernetes",
         "time_field": "",
         "where": [
          { "key": "module", "method": "eq", "value": [ "data" ] }
         ]
        }
       ]
      }
     ]
    }
   ]
  }
 ]
}