{{- if .Values.procserver.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ template "bk-cmdb.procserver" . }}"
  labels:
{{ include "bk-cmdb.labels" . | indent 4 }}
spec:
  ports:
    - port: 80
      targetPort: {{ .Values.procserver.port }}
  selector:
{{ include "bk-cmdb.matchLabels" . | indent 4 }}
    component: procserver
{{- end }}
