{{- if .Values.cacheservice.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ template "bk-cmdb.cacheservice" . }}"
  labels:
{{ include "bk-cmdb.labels" . | indent 4 }}
spec:
  ports:
    - port: 80
      targetPort: {{ .Values.cacheservice.port }}
  selector:
{{ include "bk-cmdb.matchLabels" . | indent 4 }}
    component: cacheservice
{{- end }}
