{{- if .Values.apiserver.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ template "bk-cmdb.apiserver" . }}"
  labels:
{{ include "bk-cmdb.labels" . | indent 4 }}
spec:
  ports:
    - port: 80
      targetPort: {{ .Values.apiserver.port }}
  selector:
{{ include "bk-cmdb.matchLabels" . | indent 4 }}
    component: apiserver
{{- end }}
