/*
 * Tencent is pleased to support the open source community by making
 * 蓝鲸智云 - 配置平台 (BlueKing - Configuration System) available.
 * Copyright (C) 2017 THL A29 Limited,
 * a Tencent company. All rights reserved.
 * Licensed under the MIT License (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at http://opensource.org/licenses/MIT
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the
 * specific language governing permissions and limitations under the License.
 * We undertake not to change the open source license (MIT license) applicable
 * to the current version of the project delivered to anyone in the future.
 */

package general

import (
	"fmt"
)

// UniqueKeyType defines the different unique key types of general resource cache redis key
// NOTE: UniqueKeyType's related redis key must be generated by unique field of resource data
type UniqueKeyType string

var (
	// IPCloudIDType is the host inner ip+cloud id unique key type
	IPCloudIDType UniqueKeyType = "ip_cloudID"
	// AgentIDType is the host agent id unique key type
	AgentIDType UniqueKeyType = "agentID"
)

// IPCloudIDKey returns the unique key of IPCloudIDType
func IPCloudIDKey(ip string, cloudID int64) string {
	return fmt.Sprintf("%s:%d", ip, cloudID)
}

// AgentIDKey returns the unique key of AgentIDType
func AgentIDKey(agentID string) string {
	return agentID
}
