{{- if .Values.operationserver.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ template "bk-cmdb.operationserver" . }}"
  labels:
{{ include "common.labels.standard" . | indent 4 }}
spec:
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.operationserver.port }}
  selector:
{{ include "common.labels.matchLabels" . | indent 4 }}
    component: operationserver
{{- end }}
