{{- if .Values.procserver.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ template "bk-cmdb.procserver" . }}"
  labels:
{{ include "common.labels.standard" . | indent 4 }}
spec:
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.procserver.port }}
  selector:
{{ include "common.labels.matchLabels" . | indent 4 }}
    component: procserver
{{- end }}
