FROM mirrors.tencent.com/tencentos/tencentos4-minimal
ENV container docker
COPY cmdb_apiserver /data/cmdb/cmdb_apiserver
RUN mkdir /data/cmdb/cmdb_apiserver/logs
RUN chmod +x /data/cmdb/cmdb_apiserver/cmdb_apiserver
#time zone setting
ENV TimeZone=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TimeZone /etc/localtime && echo $TimeZone > /etc/timezone

