FROM ccr.ccs.tencentyun.com/bk.io/centos7-cmdb:base
ENV container docker
COPY cmdb_toposerver /data/cmdb/cmdb_toposerver
RUN mkdir /data/cmdb/cmdb_toposerver/logs
RUN chmod +x /data/cmdb/cmdb_toposerver/cmdb_toposerver

