{{- if .Values.taskserver.enabled }}
apiVersion: {{ .Values.ApiVersion.Deployment }}
kind: Deployment
metadata:
  name: "{{ template "bk-cmdb.fullname" . }}-taskserver"
  labels:
    {{- include "bk-cmdb.labels" . | nindent 4 }}
    component: taskserver
spec:
  replicas: {{ .Values.taskserver.replicas }}
  selector:
    matchLabels:
      {{- include "bk-cmdb.matchLabels" . | nindent 6 }}
      component: taskserver
  template:
    metadata:
      labels:
        {{- include "bk-cmdb.labels" . | nindent 8 }}
        component: taskserver
      {{- with .Values.taskserver.annotations }}
      annotations:
        {{ toYaml . | indent 8 }}
      {{- end }}
      {{- if .Values.taskserver.podAnnotations }}
        {{ toYaml .Values.taskserver.podAnnotations | indent 8 }}
      {{- end }}
    spec:
      containers:
      - name: taskserver
        image: {{ .Values.taskserver.image.repository }}:{{ .Values.taskserver.image.tag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        workingDir: /data/bin/bk-cmdb/cmdb_taskserver/
        command:
        - ./cmdb_taskserver
        - --addrport=$(POD_IP):{{ .Values.taskserver.port }}
        - --regdiscv={{ .Release.Name }}-zookeeper:{{ .Values.zookeeper.service.ports.client.port }}
        {{- if .Values.taskserver.command.logDir }}
        - --log-dir
        - {{ .Values.taskserver.command.logDir }}
        {{- end }}
        {{- if .Values.taskserver.command.logLevel }}
        - --v
        - {{ .Values.taskserver.command.logLevel | quote }}
        {{- end }}
        {{- if .Values.taskserver.command.logtostderr }}
        - --logtostderr
        - {{ .Values.taskserver.command.logtostderr | quote }}
        {{- end }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.taskserver.port }}
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.taskserver.port }}
          initialDelaySeconds: 30
          periodSeconds: 10

        {{- if .Values.taskserver.resources }}
        resources:
          {{ toYaml .Values.taskserver.resources | indent 10 }}
        {{- end }}

        env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        {{- if .Values.taskserver.env }}
          {{ toYaml .Values.taskserver.env | indent 10 }}
        {{- end }}

        ports:
        - containerPort: {{ .Values.taskserver.port }}

      {{- with .Values.taskserver.nodeSelector }}
      nodeSelector:
      {{ toYaml . | indent 8 }}
      {{- end }}

      {{- with .Values.taskserver.affinity }}
      affinity:
        {{ toYaml . | indent 8 }}
      {{- end }}

      {{- with .Values.taskserver.tolerations }}
      tolerations:
        {{ toYaml . | indent 8 }}
      {{- end }}

{{- end }}
