apiVersion: v2
appVersion: 3.14.9-alpha2
description: BlueKing Configuration Management DataBase (bk-cmdb) is an enterprise level configuration management service database.
name: bk-cmdb-web
type: application
version: 3.15.9-alpha2
dependencies:
  - name: common
    repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
    version: 2.2.2
  - condition: redis.enabled
    name: redis
    repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
    version: 17.3.17
  - condition: mongodb.enabled
    name: mongodb
    repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
    version: 13.6.1
