{{- if .Values.datacollection.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ template "bk-cmdb.datacollection" . }}"
  labels:
{{ include "bk-cmdb.labels" . | indent 4 }}
spec:
  ports:
    - port: 80
      targetPort: {{ .Values.datacollection.port }}
  selector:
{{ include "bk-cmdb.matchLabels" . | indent 4 }}
    component: datacollection
{{- end }}
