FROM ccr.ccs.tencentyun.com/bk.io/centos7-cmdb:base
ENV container docker
COPY cmdb_hostserver /data/cmdb/cmdb_hostserver
RUN mkdir /data/cmdb/cmdb_hostserver/logs
RUN chmod +x /data/cmdb/cmdb_hostserver/cmdb_hostserver

