{{- if .Values.webserver.enabled }}
apiVersion: {{ .Values.ApiVersion.Deployment }}
kind: Deployment
metadata:
  name: "{{ template "bk-cmdb.fullname" . }}-webserver"
  labels:
    {{- include "bk-cmdb.labels" . | nindent 4 }}
    component: webserver
spec:
  replicas: {{ .Values.webserver.replicas }}
  selector:
    matchLabels:
      {{- include "bk-cmdb.matchLabels" . | nindent 6 }}
      component: webserver
  template:
    metadata:
      labels:
        {{- include "bk-cmdb.labels" . | nindent 8 }}
        component: webserver
      {{- with .Values.webserver.annotations }}
      annotations:
        {{ toYaml . | indent 8 }}
      {{- end }}
      {{- if .Values.webserver.podAnnotations }}
        {{ toYaml .Values.webserver.podAnnotations | indent 8 }}
      {{- end }}
    spec:
      {{- if .Values.webserver.hostNetwork }}
      hostNetwork: true
      {{- end }}
      dnsPolicy: {{ .Values.webserver.dnsPolicy }}
      containers:
      - name: webserver
        image: {{ .Values.webserver.image.repository }}:{{ .Values.webserver.image.tag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        workingDir: /data/bin/bk-cmdb/cmdb_webserver/
        command:
        - ./cmdb_webserver
        - --addrport=$(POD_IP):{{ .Values.webserver.port }}
        - --regdiscv={{ .Release.Name }}-zookeeper:{{ .Values.zookeeper.service.ports.client.port }}
        {{- if .Values.webserver.command.logDir }}
        - --log-dir
        - {{ .Values.webserver.command.logDir }}
        {{- end }}
        {{- if .Values.webserver.command.logLevel }}
        - --v
        - {{ .Values.webserver.command.logLevel | quote }}
        {{- end }}
        {{- if .Values.webserver.command.logtostderr }}
        - --logtostderr
        - {{ .Values.webserver.command.logtostderr | quote }}
        {{- end }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.webserver.port }}
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.webserver.port }}
          initialDelaySeconds: 30
          periodSeconds: 10

        {{- if .Values.webserver.resources }}
        resources:
          {{ toYaml .Values.webserver.resources | indent 10 }}
        {{- end }}

        env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        {{- if .Values.webserver.env }}
          {{ toYaml .Values.webserver.env | indent 10 }}
        {{- end }}

        ports:
        - containerPort: {{ .Values.webserver.port }}

      {{- with .Values.webserver.nodeSelector }}
      nodeSelector:
      {{ toYaml . | indent 8 }}
      {{- end }}

      {{- with .Values.webserver.affinity }}
      affinity:
        {{ toYaml . | indent 8 }}
      {{- end }}

      {{- with .Values.webserver.tolerations }}
      tolerations:
        {{ toYaml . | indent 8 }}
      {{- end }}

{{- end }}
