{{- if .Values.webserver.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ template "bk-cmdb.webserver" . }}"
  labels:
{{ include "bk-cmdb.labels" . | indent 4 }}
spec:
  type: {{ .Values.webserver.service.type }}
  ports:
  {{- with .Values.webserver.service.ports }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  # ports:
  #   - port: 80
  #     targetPort: {{ .Values.webserver.port }}
  selector:
{{ include "bk-cmdb.matchLabels" . | indent 4 }}
    component: webserver
{{- end }}
