FROM hub.bktencent.com/blueking/centos7-cmdb:base
ENV container docker
COPY cmdb_authserver /data/cmdb/cmdb_authserver
RUN mkdir /data/cmdb/cmdb_authserver/logs
RUN chmod +x /data/cmdb/cmdb_authserver/cmdb_authserver
#time zone setting
ENV TimeZone=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TimeZone /etc/localtime && echo $TimeZone > /etc/timezone