name: bk-cmdb
version: 0.1.19
appVersion: dev
description: An open source trusted cloud native registry that stores, signs, and scans content
keywords:
- cmdb
- blueking
home: https://bk.tencent.com/
icon: https://raw.githubusercontent.com/Tencent/bk-cmdb/master/docs/resource/img/BKCN.jpg
sources:
- https://github.com/Tencent/bk-cmdb
- https://github.com/Tencent/bk-cmdb-helm
maintainers:
- name: blueking
  email: blueking@tencent.com
engine: gotpl
