FROM ccr.ccs.tencentyun.com/bk.io/centos7-cmdb:base
ENV container docker
COPY cmdb_cloudserver /data/cmdb/cmdb_cloudserver
RUN mkdir /data/cmdb/cmdb_cloudserver/logs
RUN chmod +x /data/cmdb/cmdb_cloudserver/cmdb_cloudserver
#time zone setting
ENV TimeZone=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TimeZone /etc/localtime && echo $TimeZone > /etc/timezone