FROM ccr.ccs.tencentyun.com/bk.io/centos7-cmdb:base
ENV container docker
COPY cmdb_apiserver /data/cmdb/cmdb_apiserver
RUN mkdir /data/cmdb/cmdb_apiserver/logs
RUN chmod +x /data/cmdb/cmdb_apiserver/cmdb_apiserver

