{{- if .Values.synchronizeserver.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ template "bk-cmdb.synchronizeserver" . }}"
  labels:
{{ include "common.labels.standard" . | indent 4 }}
spec:
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.synchronizeserver.port }}
  selector:
{{ include "common.labels.matchLabels" . | indent 4 }}
    component: synchronizeserver
{{- end }}
