version: '3.8'
services:
  cache:
    image: harbor.dev.21vianet.com/cmdb/redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 180 1 --loglevel warning --requirepass cc
    volumes: 
      - cache:/data
volumes:
  cache:
    driver: local
