// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: auth_server.proto

package authpb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Basic defines the basic info of an auth resource.
type Basic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Id            string                 `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Basic) Reset() {
	*x = Basic{}
	mi := &file_auth_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Basic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Basic) ProtoMessage() {}

func (x *Basic) ProtoReflect() protoreflect.Message {
	mi := &file_auth_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Basic.ProtoReflect.Descriptor instead.
func (*Basic) Descriptor() ([]byte, []int) {
	return file_auth_server_proto_rawDescGZIP(), []int{0}
}

func (x *Basic) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Basic) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *Basic) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Basic) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// ResourceAttribute represents one iam resource.
type ResourceAttribute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Basic         *Basic                 `protobuf:"bytes,1,opt,name=basic,proto3" json:"basic,omitempty"`
	Layers        []*Basic               `protobuf:"bytes,2,rep,name=layers,proto3" json:"layers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceAttribute) Reset() {
	*x = ResourceAttribute{}
	mi := &file_auth_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceAttribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceAttribute) ProtoMessage() {}

func (x *ResourceAttribute) ProtoReflect() protoreflect.Message {
	mi := &file_auth_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceAttribute.ProtoReflect.Descriptor instead.
func (*ResourceAttribute) Descriptor() ([]byte, []int) {
	return file_auth_server_proto_rawDescGZIP(), []int{1}
}

func (x *ResourceAttribute) GetBasic() *Basic {
	if x != nil {
		return x.Basic
	}
	return nil
}

func (x *ResourceAttribute) GetLayers() []*Basic {
	if x != nil {
		return x.Layers
	}
	return nil
}

// AuthorizeReq is the authorize request.
type AuthorizeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resources     []*ResourceAttribute   `protobuf:"bytes,1,rep,name=resources,proto3" json:"resources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizeReq) Reset() {
	*x = AuthorizeReq{}
	mi := &file_auth_server_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeReq) ProtoMessage() {}

func (x *AuthorizeReq) ProtoReflect() protoreflect.Message {
	mi := &file_auth_server_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeReq.ProtoReflect.Descriptor instead.
func (*AuthorizeReq) Descriptor() ([]byte, []int) {
	return file_auth_server_proto_rawDescGZIP(), []int{2}
}

func (x *AuthorizeReq) GetResources() []*ResourceAttribute {
	if x != nil {
		return x.Resources
	}
	return nil
}

// Decision is the authorize decision.
type Decision struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Authorized    bool                   `protobuf:"varint,1,opt,name=authorized,proto3" json:"authorized,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Decision) Reset() {
	*x = Decision{}
	mi := &file_auth_server_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Decision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Decision) ProtoMessage() {}

func (x *Decision) ProtoReflect() protoreflect.Message {
	mi := &file_auth_server_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Decision.ProtoReflect.Descriptor instead.
func (*Decision) Descriptor() ([]byte, []int) {
	return file_auth_server_proto_rawDescGZIP(), []int{3}
}

func (x *Decision) GetAuthorized() bool {
	if x != nil {
		return x.Authorized
	}
	return false
}

// AuthorizeResp is the authorize response.
type AuthorizeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Decisions     []*Decision            `protobuf:"bytes,1,rep,name=decisions,proto3" json:"decisions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizeResp) Reset() {
	*x = AuthorizeResp{}
	mi := &file_auth_server_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeResp) ProtoMessage() {}

func (x *AuthorizeResp) ProtoReflect() protoreflect.Message {
	mi := &file_auth_server_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeResp.ProtoReflect.Descriptor instead.
func (*AuthorizeResp) Descriptor() ([]byte, []int) {
	return file_auth_server_proto_rawDescGZIP(), []int{4}
}

func (x *AuthorizeResp) GetDecisions() []*Decision {
	if x != nil {
		return x.Decisions
	}
	return nil
}

// ListAuthResReq is the list authorized resource request.
type ListAuthResReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceType  string                 `protobuf:"bytes,1,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAuthResReq) Reset() {
	*x = ListAuthResReq{}
	mi := &file_auth_server_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuthResReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuthResReq) ProtoMessage() {}

func (x *ListAuthResReq) ProtoReflect() protoreflect.Message {
	mi := &file_auth_server_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuthResReq.ProtoReflect.Descriptor instead.
func (*ListAuthResReq) Descriptor() ([]byte, []int) {
	return file_auth_server_proto_rawDescGZIP(), []int{5}
}

func (x *ListAuthResReq) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *ListAuthResReq) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

// ListAuthResResp is the list authorized resource response.
type ListAuthResResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	IsAny         bool                   `protobuf:"varint,2,opt,name=is_any,json=isAny,proto3" json:"is_any,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAuthResResp) Reset() {
	*x = ListAuthResResp{}
	mi := &file_auth_server_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuthResResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuthResResp) ProtoMessage() {}

func (x *ListAuthResResp) ProtoReflect() protoreflect.Message {
	mi := &file_auth_server_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuthResResp.ProtoReflect.Descriptor instead.
func (*ListAuthResResp) Descriptor() ([]byte, []int) {
	return file_auth_server_proto_rawDescGZIP(), []int{6}
}

func (x *ListAuthResResp) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *ListAuthResResp) GetIsAny() bool {
	if x != nil {
		return x.IsAny
	}
	return false
}

var File_auth_server_proto protoreflect.FileDescriptor

const file_auth_server_proto_rawDesc = "" +
	"\n" +
	"\x11auth_server.proto\x12\vauth_server\x1a\x1cgoogle/api/annotations.proto\"W\n" +
	"\x05Basic\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\tR\x02id\"i\n" +
	"\x11ResourceAttribute\x12(\n" +
	"\x05basic\x18\x01 \x01(\v2\x12.auth_server.BasicR\x05basic\x12*\n" +
	"\x06layers\x18\x02 \x03(\v2\x12.auth_server.BasicR\x06layers\"L\n" +
	"\fAuthorizeReq\x12<\n" +
	"\tresources\x18\x01 \x03(\v2\x1e.auth_server.ResourceAttributeR\tresources\"*\n" +
	"\bDecision\x12\x1e\n" +
	"\n" +
	"authorized\x18\x01 \x01(\bR\n" +
	"authorized\"D\n" +
	"\rAuthorizeResp\x123\n" +
	"\tdecisions\x18\x01 \x03(\v2\x15.auth_server.DecisionR\tdecisions\"M\n" +
	"\x0eListAuthResReq\x12#\n" +
	"\rresource_type\x18\x01 \x01(\tR\fresourceType\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\":\n" +
	"\x0fListAuthResResp\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\x12\x15\n" +
	"\x06is_any\x18\x02 \x01(\bR\x05isAny2\x95\x02\n" +
	"\x04Auth\x12e\n" +
	"\tAuthorize\x12\x19.auth_server.AuthorizeReq\x1a\x1a.auth_server.AuthorizeResp\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/api/v4/auth/authorize\x12V\n" +
	"\x17ListAuthorizedResources\x12\x1b.auth_server.ListAuthResReq\x1a\x1c.auth_server.ListAuthResResp\"\x00\x12N\n" +
	"\x0fAuthorizeStream\x12\x19.auth_server.AuthorizeReq\x1a\x1a.auth_server.AuthorizeResp\"\x00(\x010\x01BAZ?github.com/TencentBlueKing/bk-cmdb/pkg/proto/auth-server;authpbb\x06proto3"

var (
	file_auth_server_proto_rawDescOnce sync.Once
	file_auth_server_proto_rawDescData []byte
)

func file_auth_server_proto_rawDescGZIP() []byte {
	file_auth_server_proto_rawDescOnce.Do(func() {
		file_auth_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_server_proto_rawDesc), len(file_auth_server_proto_rawDesc)))
	})
	return file_auth_server_proto_rawDescData
}

var file_auth_server_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_auth_server_proto_goTypes = []any{
	(*Basic)(nil),             // 0: auth_server.Basic
	(*ResourceAttribute)(nil), // 1: auth_server.ResourceAttribute
	(*AuthorizeReq)(nil),      // 2: auth_server.AuthorizeReq
	(*Decision)(nil),          // 3: auth_server.Decision
	(*AuthorizeResp)(nil),     // 4: auth_server.AuthorizeResp
	(*ListAuthResReq)(nil),    // 5: auth_server.ListAuthResReq
	(*ListAuthResResp)(nil),   // 6: auth_server.ListAuthResResp
}
var file_auth_server_proto_depIdxs = []int32{
	0, // 0: auth_server.ResourceAttribute.basic:type_name -> auth_server.Basic
	0, // 1: auth_server.ResourceAttribute.layers:type_name -> auth_server.Basic
	1, // 2: auth_server.AuthorizeReq.resources:type_name -> auth_server.ResourceAttribute
	3, // 3: auth_server.AuthorizeResp.decisions:type_name -> auth_server.Decision
	2, // 4: auth_server.Auth.Authorize:input_type -> auth_server.AuthorizeReq
	5, // 5: auth_server.Auth.ListAuthorizedResources:input_type -> auth_server.ListAuthResReq
	2, // 6: auth_server.Auth.AuthorizeStream:input_type -> auth_server.AuthorizeReq
	4, // 7: auth_server.Auth.Authorize:output_type -> auth_server.AuthorizeResp
	6, // 8: auth_server.Auth.ListAuthorizedResources:output_type -> auth_server.ListAuthResResp
	4, // 9: auth_server.Auth.AuthorizeStream:output_type -> auth_server.AuthorizeResp
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_auth_server_proto_init() }
func file_auth_server_proto_init() {
	if File_auth_server_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_server_proto_rawDesc), len(file_auth_server_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_server_proto_goTypes,
		DependencyIndexes: file_auth_server_proto_depIdxs,
		MessageInfos:      file_auth_server_proto_msgTypes,
	}.Build()
	File_auth_server_proto = out.File
	file_auth_server_proto_goTypes = nil
	file_auth_server_proto_depIdxs = nil
}
