// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: auth_server.proto

package authpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Auth_Authorize_FullMethodName               = "/auth_server.Auth/Authorize"
	Auth_ListAuthorizedResources_FullMethodName = "/auth_server.Auth/ListAuthorizedResources"
	Auth_AuthorizeStream_FullMethodName         = "/auth_server.Auth/AuthorizeStream"
)

// AuthClient is the client API for Auth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthClient interface {
	// Authorize checks whether the user has permission to operate resources.
	Authorize(ctx context.Context, in *AuthorizeReq, opts ...grpc.CallOption) (*AuthorizeResp, error)
	// ListAuthorizedResources lists the resources that the user has permission to operate.
	ListAuthorizedResources(ctx context.Context, in *ListAuthResReq, opts ...grpc.CallOption) (*ListAuthResResp, error)
	// AuthorizeStream this is only a demo for streaming.
	AuthorizeStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AuthorizeReq, AuthorizeResp], error)
}

type authClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthClient(cc grpc.ClientConnInterface) AuthClient {
	return &authClient{cc}
}

func (c *authClient) Authorize(ctx context.Context, in *AuthorizeReq, opts ...grpc.CallOption) (*AuthorizeResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthorizeResp)
	err := c.cc.Invoke(ctx, Auth_Authorize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) ListAuthorizedResources(ctx context.Context, in *ListAuthResReq, opts ...grpc.CallOption) (*ListAuthResResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAuthResResp)
	err := c.cc.Invoke(ctx, Auth_ListAuthorizedResources_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) AuthorizeStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AuthorizeReq, AuthorizeResp], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Auth_ServiceDesc.Streams[0], Auth_AuthorizeStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AuthorizeReq, AuthorizeResp]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Auth_AuthorizeStreamClient = grpc.BidiStreamingClient[AuthorizeReq, AuthorizeResp]

// AuthServer is the server API for Auth service.
// All implementations must embed UnimplementedAuthServer
// for forward compatibility.
type AuthServer interface {
	// Authorize checks whether the user has permission to operate resources.
	Authorize(context.Context, *AuthorizeReq) (*AuthorizeResp, error)
	// ListAuthorizedResources lists the resources that the user has permission to operate.
	ListAuthorizedResources(context.Context, *ListAuthResReq) (*ListAuthResResp, error)
	// AuthorizeStream this is only a demo for streaming.
	AuthorizeStream(grpc.BidiStreamingServer[AuthorizeReq, AuthorizeResp]) error
	mustEmbedUnimplementedAuthServer()
}

// UnimplementedAuthServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthServer struct{}

func (UnimplementedAuthServer) Authorize(context.Context, *AuthorizeReq) (*AuthorizeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Authorize not implemented")
}
func (UnimplementedAuthServer) ListAuthorizedResources(context.Context, *ListAuthResReq) (*ListAuthResResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAuthorizedResources not implemented")
}
func (UnimplementedAuthServer) AuthorizeStream(grpc.BidiStreamingServer[AuthorizeReq, AuthorizeResp]) error {
	return status.Errorf(codes.Unimplemented, "method AuthorizeStream not implemented")
}
func (UnimplementedAuthServer) mustEmbedUnimplementedAuthServer() {}
func (UnimplementedAuthServer) testEmbeddedByValue()              {}

// UnsafeAuthServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServer will
// result in compilation errors.
type UnsafeAuthServer interface {
	mustEmbedUnimplementedAuthServer()
}

func RegisterAuthServer(s grpc.ServiceRegistrar, srv AuthServer) {
	// If the following call pancis, it indicates UnimplementedAuthServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Auth_ServiceDesc, srv)
}

func _Auth_Authorize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthorizeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).Authorize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Auth_Authorize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).Authorize(ctx, req.(*AuthorizeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_ListAuthorizedResources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAuthResReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).ListAuthorizedResources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Auth_ListAuthorizedResources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).ListAuthorizedResources(ctx, req.(*ListAuthResReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_AuthorizeStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AuthServer).AuthorizeStream(&grpc.GenericServerStream[AuthorizeReq, AuthorizeResp]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Auth_AuthorizeStreamServer = grpc.BidiStreamingServer[AuthorizeReq, AuthorizeResp]

// Auth_ServiceDesc is the grpc.ServiceDesc for Auth service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Auth_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth_server.Auth",
	HandlerType: (*AuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Authorize",
			Handler:    _Auth_Authorize_Handler,
		},
		{
			MethodName: "ListAuthorizedResources",
			Handler:    _Auth_ListAuthorizedResources_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AuthorizeStream",
			Handler:       _Auth_AuthorizeStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "auth_server.proto",
}
