{{- if .Values.hostserver.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ template "bk-cmdb.hostserver" . }}"
  labels:
{{ include "common.labels.standard" . | indent 4 }}
spec:
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.hostserver.port }}
  selector:
{{ include "common.labels.matchLabels" . | indent 4 }}
    component: hostserver
{{- end }}
