{{- if .Values.migrate.migrateDataId }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "bk-cmdb.fullname" . }}-migrate-dataid-{{ .Release.Revision }}
  labels:
    app: {{ template "bk-cmdb.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
  annotations:
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-weight": "-4"
spec:
  ttlSecondsAfterFinished: 600
  completions: 1
  parallelism: 1
  template:
    spec:
      containers:
      - name: cmdb-migratedataid
        image: {{ template "cmdb.basicImagesAddress" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
        - sh
        - "-c"
        - |
          /bin/bash <<'EOF'
          res=$(curl -s -X POST \
          -H 'Content-Type:application/json' \
          -H 'X-Bkcmdb-User:migrate' \
          -H 'X-Bkcmdb-Supplier-Account:0' \
          "http://{{ template "bk-cmdb.adminserver" . }}:80/migrate/v3/migrate/dataid"
          )
          echo "$res"
          if ! [[ $(echo "$res" | jq -r .result) = "true" ]]; then
            echo "migrate data id to gse failed."
            exit 1
          fi
          EOF
        resources:
          limits:
            cpu: 200m
            memory: 1024Mi
          requests:
            memory: 512Mi
            cpu: 200m
      restartPolicy: OnFailure
  backoffLimit: 20
{{- end }}
