FROM mirrors.tencent.com/tencentos/tencentos4-minimal
ENV container docker
COPY cmdb_transferservice /data/cmdb/cmdb_transferservice
RUN mkdir /data/cmdb/cmdb_transferservice/logs
RUN chmod +x /data/cmdb/cmdb_transferservice/cmdb_transferservice
#time zone setting
ENV TimeZone=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TimeZone /etc/localtime && echo $TimeZone > /etc/timezone
