apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configures
data:
{{/*
  {{- $files := .Files }}
  {{- range tuple "apiserver.conf" "auditcontroller.conf" "coreservice.conf" "datacollection.conf" "eventserver.conf" "host.conf" "hostcontroller.conf" "migrate.conf" "objectcontroller.conf" "proc.conf" "proccontroller.conf" "topo.conf" "txc.conf" "webserver.conf" }}
  {{ . }}: |-
    {{ printf "configures/%s" . | $files.Get }}
  {{- end }}
*/}}
  apiserver.conf: |-
    [auth]
    address = http://iam.blueking.com/
    appCode = bk_cmdb
    appSecret = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  auditcontroller.conf: |-
    [mongodb]
    host = {{ .Release.Name }}-mongodb
    usr = {{ .Values.mongodb.mongodbUsername }}
    pwd = {{ .Values.mongodb.mongodbPassword }}
    database = {{ .Values.mongodb.mongodbDatabase }}
    port = {{ .Values.mongodb.service.port }}
    maxOpenConns = 3000
    maxIdleConns = 1000
    mechanism=SCRAM-SHA-1
    enable=true
  coreservice.conf: |-
    [mongodb]
    host = {{ .Release.Name }}-mongodb
    usr = {{ .Values.mongodb.mongodbUsername }}
    pwd = {{ .Values.mongodb.mongodbPassword }}
    database = {{ .Values.mongodb.mongodbDatabase }}
    port = {{ .Values.mongodb.service.port }}
    maxOpenConns = 3000
    maxIdleConns = 1000
    mechanism=SCRAM-SHA-1
    enable=true

    [redis]
    host={{ .Release.Name }}-redis-master
    usr=root
    pwd={{ .Values.redis.password }}
    database=0
    port={{ .Values.redis.master.port }}
    maxOpenConns=3000
    maxIDleConns=1000

  datacollection.conf: |-
    [mongodb]
    host = {{ .Release.Name }}-mongodb
    usr = {{ .Values.mongodb.mongodbUsername }}
    pwd = {{ .Values.mongodb.mongodbPassword }}
    database = {{ .Values.mongodb.mongodbDatabase }}
    port = {{ .Values.mongodb.service.port }}
    maxOpenConns = 3000
    maxIdleConns = 1000
    mechanism=SCRAM-SHA-1
    enable=true

    [snap-redis]
    host = {{ .Release.Name }}-redis-master:{{ .Values.redis.master.port}}
    usr = root
    pwd = {{ .Values.redis.password }}
    database = 0

    [discover-redis]
    host = {{ .Release.Name }}-redis-master:{{ .Values.redis.master.port}}
    usr = root
    pwd = {{ .Values.redis.password }}
    database = 0

    [netcollect-redis]
    host = {{ .Release.Name }}-redis-master:{{ .Values.redis.master.port}}
    usr = root
    pwd = {{ .Values.redis.password }}
    database = 0

    [redis]
    host = {{ .Release.Name }}-redis-master:{{ .Values.redis.master.port}}
    usr = root
    pwd = {{ .Values.redis.password }}
    database = 0

  eventserver.conf: |-
    [mongodb]
    host = {{ .Release.Name }}-mongodb
    usr = {{ .Values.mongodb.mongodbUsername }}
    pwd = {{ .Values.mongodb.mongodbPassword }}
    database = {{ .Values.mongodb.mongodbDatabase }}
    port = {{ .Values.mongodb.service.port }}
    maxOpenConns = 3000
    maxIdleConns = 1000
    mechanism=SCRAM-SHA-1
    enable=true

    [redis]
    host={{ .Release.Name }}-redis-master
    usr=root
    pwd={{ .Values.redis.password }}
    database=0
    port={{ .Values.redis.master.port}}
    maxOpenConns=3000
    maxIDleConns=1000

  host.conf: |-
    [gse]
    addr={{ .Release.Name }}-zookeeper:{{ .Values.zookeeper.service.ports.client.port }}
    user=bkzk
    pwd=L%blKas

    [redis]
    host={{ .Release.Name }}-redis-master
    usr=root
    pwd={{ .Values.redis.password }}
    database=0
    port={{ .Values.redis.master.port}}
    maxOpenConns=3000
    maxIDleConns=1000

  hostcontroller.conf: |-
    [mongodb]
    host = {{ .Release.Name }}-mongodb
    usr = {{ .Values.mongodb.mongodbUsername }}
    pwd = {{ .Values.mongodb.mongodbPassword }}
    database = {{ .Values.mongodb.mongodbDatabase }}
    port = {{ .Values.mongodb.service.port }}
    maxOpenConns = 3000
    maxIdleConns = 1000
    mechanism=SCRAM-SHA-1
    enable=true

    [redis]
    host={{ .Release.Name }}-redis-master
    usr=root
    pwd={{ .Values.redis.password }}
    database=0
    port={{ .Values.redis.master.port}}
    maxOpenConns=3000
    maxIDleConns=1000

  migrate.conf: |-
    [config-server]
    addrs={{ .Release.Name }}-zookeeper:{{ .Values.zookeeper.service.ports.client.port }}
    usr=
    pwd=

    [register-server]
    addrs={{ .Release.Name }}-zookeeper:{{ .Values.zookeeper.service.ports.client.port }}
    usr=
    pwd=

    [mongodb]
    host = {{ .Release.Name }}-mongodb
    usr = {{ .Values.mongodb.mongodbUsername }}
    pwd = {{ .Values.mongodb.mongodbPassword }}
    database = {{ .Values.mongodb.mongodbDatabase }}
    port = {{ .Values.mongodb.service.port }}
    maxOpenConns = 3000
    maxIdleConns = 1000
    mechanism=SCRAM-SHA-1
    enable=true

    [confs]
    dir = /etc/configures/

    [errors]
    res=conf/errors

    [language]
    res=conf/language


  objectcontroller.conf: |-
    [mongodb]
    host = {{ .Release.Name }}-mongodb
    usr = {{ .Values.mongodb.mongodbUsername }}
    pwd = {{ .Values.mongodb.mongodbPassword }}
    database = {{ .Values.mongodb.mongodbDatabase }}
    port = {{ .Values.mongodb.service.port }}
    maxOpenConns = 3000
    maxIdleConns = 1000
    mechanism=SCRAM-SHA-1
    enable=true

    [redis]
    host={{ .Release.Name }}-redis-master
    usr=root
    pwd={{ .Values.redis.password }}
    database=0
    port=6379
    maxOpenConns=3000
    maxIDleConns=1000

  proc.conf: |-
    [redis]
    host={{ .Release.Name }}-redis-master
    usr=root
    pwd={{ .Values.redis.password }}
    port={{ .Values.redis.master.port}}
    database = 0

  proccontroller.conf: |-
    [mongodb]
    host = {{ .Release.Name }}-mongodb
    usr = {{ .Values.mongodb.mongodbUsername }}
    pwd = {{ .Values.mongodb.mongodbPassword }}
    database = {{ .Values.mongodb.mongodbDatabase }}
    port = {{ .Values.mongodb.service.port }}
    maxOpenConns = 3000
    maxIdleConns = 1000
    mechanism=SCRAM-SHA-1
    enable=true

    [redis]
    host={{ .Release.Name }}-redis-master
    usr=root
    pwd={{ .Values.redis.password }}
    database=0
    port={{ .Values.redis.master.port}}
    maxOpenConns=3000
    maxIDleConns=1000

  topo.conf: |-
    [mongodb]
    host = {{ .Release.Name }}-mongodb
    usr = {{ .Values.mongodb.mongodbUsername }}
    pwd = {{ .Values.mongodb.mongodbPassword }}
    database = {{ .Values.mongodb.mongodbDatabase }}
    port = {{ .Values.mongodb.service.port }}
    maxOpenConns = 3000
    maxIdleConns = 1000
    mechanism=SCRAM-SHA-1
    enable=true

    [level]
    businessTopoMax=7

  txc.conf: |-
    [mongodb]
    host = {{ .Release.Name }}-mongodb
    usr = {{ .Values.mongodb.mongodbUsername }}
    pwd = {{ .Values.mongodb.mongodbPassword }}
    database = {{ .Values.mongodb.mongodbDatabase }}
    port = {{ .Values.mongodb.service.port }}
    maxOpenConns = 3000
    maxIdleConns = 1000
    mechanism=SCRAM-SHA-1
    enable=true

    [redis]
    host={{ .Release.Name }}-redis-master
    usr=root
    pwd={{ .Values.redis.password }}
    database=0
    port={{ .Values.redis.master.port}}
    maxOpenConns=3000
    maxIDleConns=1000

    [transaction]
    enable=false
    transactionLifetimeSecond=60

  webserver.conf: |-
    [api]
    version=v3

    [session]
    name=cc3
    skip=1
    defaultlanguage=zh-cn
    host={{ .Release.Name }}-redis-master
    port={{ .Values.redis.master.port}}
    secret={{ .Values.redis.password }}
    multiple_owner=0

    [site]
    domain_url=http://{{ .Values.expose.ingress.hosts.core }}
    app_code=cc
    check_url=http://127.0.0.1:8088/login/accounts/get_user/?bk_token=
    bk_account_url=http://127.0.0.1:8088/login/accounts/get_all_user/?bk_token=%s
    resources_path=/tmp/
    html_root=../web

    [app]
    agent_app_url=http://127.0.0.1:8088/console/?app=bk_agent_setup
  task.conf: |-
    [mongodb]
    host = {{ .Release.Name }}-mongodb
    usr = {{ .Values.mongodb.mongodbUsername }}
    pwd = {{ .Values.mongodb.mongodbPassword }}
    database = {{ .Values.mongodb.mongodbDatabase }}
    port = {{ .Values.mongodb.service.port }}
    maxOpenConns = 3000
    maxIdleConns = 1000
    mechanism=SCRAM-SHA-1
    enable=true

    [redis]
    host={{ .Release.Name }}-redis-master
    usr=root
    pwd={{ .Values.redis.password }}
    database=0
    port={{ .Values.redis.master.port}}
    maxOpenConns=3000
    maxIDleConns=1000

    [transaction]
    enable=false
    transactionLifetimeSecond=60
  operation.conf: |-
    [mongodb]
    host = {{ .Release.Name }}-mongodb
    usr = {{ .Values.mongodb.mongodbUsername }}
    pwd = {{ .Values.mongodb.mongodbPassword }}
    database = {{ .Values.mongodb.mongodbDatabase }}
    port = {{ .Values.mongodb.service.port }}
    maxOpenConns = 3000
    maxIdleConns = 1000
    mechanism=SCRAM-SHA-1
    enable=true

    [timer]
    spec = 00:30  # 00:00 - 23:59

