{{- if .Values.migrate.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "bk-cmdb.fullname" . }}-bootstrap
  labels:
    app: {{ template "bk-cmdb.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  template:
    metadata:
      name: {{ template "bk-cmdb.fullname" . }}-bootstrap
      labels:
        app: {{ template "bk-cmdb.name" . }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      containers:
      - name: cmdb-migrate
        image: {{ .Values.migrate.image.repository }}:{{ .Values.migrate.image.tag }}
        imagePullPolicy: IfNotPresent
        command:
        - curl
        - -X
        - POST
        - -H
        - 'Content-Type:application/json'
        - -H
        - 'BK_USER:migrate'
        - -H
        - 'HTTP_BLUEKING_SUPPLIER_ID:0'
        - "http://{{ template "bk-cmdb.adminserver" . }}:80/migrate/v3/migrate/community/0"
        volumeMounts:
        - name: configures
          mountPath: /etc/configures
      restartPolicy: OnFailure
      volumes:
      - name: configures
        configMap:
          name: {{ .Release.Name }}-configures
  backoffLimit: 20
{{- end }}
