FROM ccr.ccs.tencentyun.com/bk.io/centos7-cmdb:base
ENV container docker
COPY cmdb_cacheservice /data/cmdb/cmdb_cacheservice
RUN mkdir /data/cmdb/cmdb_cacheservice/logs
RUN chmod +x /data/cmdb/cmdb_cacheservice/cmdb_cacheservice