# 注册中心
registerServer:
  addrs: __BK_CMDB_ZK_ADDR__

# 指定configures的路径，通过这个路径找到其他的配置文件
confs:
  dir: __BK_HOME__/cmdb/server/conf
# 指定errors的路径
errors:
  res: __BK_HOME__/cmdb/errors
# 指定language的路径
language:
  res: __BK_HOME__/cmdb/language
hostsnap:
# 主机静态数据采集专用dataid
  dataID: 1100010
# migrate dataid时的相关配置
dataid:
  # 通过何种方式调用gse接口注册dataid, 可选值esb和apigw, 如果填写esb则必须配置common.yaml的esb配置, 如果填写apigw则必须配置common.yaml的apiGW配置,不填默认为esb
  migrateWay: esb
