{{- if .Values.taskserver.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ template "bk-cmdb.taskserver" . }}"
  labels:
{{ include "bk-cmdb.labels" . | indent 4 }}
spec:
  ports:
    - port: 80
      targetPort: {{ .Values.taskserver.port }}
  selector:
{{ include "bk-cmdb.matchLabels" . | indent 4 }}
    component: taskserver
{{- end }}
