FROM hub.bktencent.com/blueking/centos7-cmdb:base
ENV container docker
COPY cmdb_coreservice /data/cmdb/cmdb_coreservice
RUN mkdir /data/cmdb/cmdb_coreservice/logs
RUN chmod +x /data/cmdb/cmdb_coreservice/cmdb_coreservice
#time zone setting
ENV TimeZone=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TimeZone /etc/localtime && echo $TimeZone > /etc/timezone

