FROM ccr.ccs.tencentyun.com/bk.io/centos7-cmdb:base
ENV container docker
COPY cmdb_coreservice /data/cmdb/cmdb_coreservice
RUN mkdir /data/cmdb/cmdb_coreservice/logs
RUN chmod +x /data/cmdb/cmdb_coreservice/cmdb_coreservice

