FROM mirrors.tencent.com/tencentos/tencentos3-minimal
ENV container docker
COPY cmdb_webserver /data/cmdb/cmdb_webserver
RUN mkdir /data/cmdb/cmdb_webserver/logs
RUN chmod +x /data/cmdb/cmdb_webserver/cmdb_webserver
#time zone setting
ENV TimeZone=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TimeZone /etc/localtime && echo $TimeZone > /etc/timezone

