{{- if .Values.apiserver.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ template "bk-cmdb.apiserver" . }}"
  labels:
{{ include "common.labels.standard" . | indent 4 }}
spec:
  type: {{ .Values.apiserver.service.type }}
  ports:
  {{- with .Values.apiserver.service.ports }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
{{ include "common.labels.matchLabels" . | indent 4 }}
    component: apiserver
{{- end }}
