{{- if .Values.apiserver.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ template "bk-cmdb.apiserver" . }}"
  labels:
{{ include "common.labels.standard" . | indent 4 }}
spec:
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.apiserver.port }}
  selector:
{{ include "common.labels.matchLabels" . | indent 4 }}
    component: apiserver
{{- end }}
