swagger: '2.0'
basePath: /
info:
  version: '0.1'
  title: API Gateway Resources
  description: ''
schemes:
- http
paths:
  /api/v3/cache/find/biz/kube/topo:
    post:
      operationId: get_biz_kube_cache_topo
      description: 查询业务的容器拓扑树缓存信息，包含业务、Cluster、Namespace、Workload层级的数据
      tags:
      - job
      - topo
      - kube
      responses:
        default:
          description: ''
      x-bk-apigateway-resource:
        isPublic: false
        allowApplyPermission: false
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v3/cache/find/biz/kube/topo
          matchSubpath: false
          timeout: 0
          upstreams: {}
          transformHeaders: {}
        authConfig:
          userVerifiedRequired: false
        disabledStages: []
        descriptionEn:
  /api/v3/findmany/kube/container/by_topo:
    post:
      operationId: list_kube_container_by_topo
      description: 根据容器拓扑获取container信息
      tags:
      - job
      - topo
      - kube
      responses:
        default:
          description: ''
      x-bk-apigateway-resource:
        isPublic: false
        allowApplyPermission: false
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v3/findmany/kube/container/by_topo
          matchSubpath: false
          timeout: 0
          upstreams: {}
          transformHeaders: {}
        authConfig:
          userVerifiedRequired: false
        disabledStages: []
        descriptionEn:
  /api/v3/findmany/kube/cluster:
    post:
      operationId: list_kube_cluster
      description: 查询容器集群
      tags:
        - kube
      responses:
        default:
          description: ''
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v3/findmany/kube/cluster
          matchSubpath: false
          timeout: 0
          upstreams: {}
          transformHeaders: {}
        authConfig:
          userVerifiedRequired: false
        disabledStages: []
        descriptionEn:
  /api/v3/findmany/kube/container:
    post:
      operationId: list_kube_container
      description: 查询Container列表
      tags:
        - kube
      responses:
        default:
          description: ''
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v3/findmany/kube/container
          matchSubpath: false
          timeout: 0
          upstreams: {}
          transformHeaders: {}
        authConfig:
          userVerifiedRequired: false
        disabledStages: []
        descriptionEn:
  /api/v3/findmany/kube/namespace:
    post:
      operationId: list_kube_namespace
      description: 查询namespace
      tags:
        - kube
      responses:
        default:
          description: ''
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v3/findmany/kube/namespace
          matchSubpath: false
          timeout: 0
          upstreams: {}
          transformHeaders: {}
        authConfig:
          userVerifiedRequired: false
        disabledStages: []
        descriptionEn:
  /api/v3/findmany/kube/node:
    post:
      operationId: list_kube_node
      description: 查询容器节点
      tags:
        - kube
      responses:
        default:
          description: ''
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v3/findmany/kube/node
          matchSubpath: false
          timeout: 0
          upstreams: {}
          transformHeaders: {}
        authConfig:
          userVerifiedRequired: false
        disabledStages: []
        descriptionEn:
  /api/v3/findmany/kube/pod:
    post:
      operationId: list_kube_pod
      description: 查询Pod列表
      tags:
        - kube
      responses:
        default:
          description: ''
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v3/findmany/kube/pod
          matchSubpath: false
          timeout: 0
          upstreams: {}
          transformHeaders: {}
        authConfig:
          userVerifiedRequired: false
        disabledStages: []
        descriptionEn:
  /api/v3/findmany/kube/workload/{kind}:
    post:
      operationId: list_kube_workload
      description: 查询workload
      tags:
        - kube
      responses:
        default:
          description: ''
      x-bk-apigateway-resource:
        isPublic: true
        allowApplyPermission: true
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v3/findmany/kube/workload/{kind}
          matchSubpath: false
          timeout: 0
          upstreams: {}
          transformHeaders: {}
        authConfig:
          userVerifiedRequired: false
        disabledStages: []
        descriptionEn:
  /api/v3/cache/findmany/kube/pod/label/key:
    post:
      operationId: list_cached_kube_pod_label_key
      description: 获取缓存的Pod的标签键列表
      tags:
        - job
        - kube
      responses:
        default:
          description: ''
      x-bk-apigateway-resource:
        isPublic: false
        allowApplyPermission: false
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v3/cache/findmany/kube/pod/label/key
          matchSubpath: false
          timeout: 0
          upstreams: {}
          transformHeaders: {}
        authConfig:
          userVerifiedRequired: false
        disabledStages: []
        descriptionEn:
  /api/v3/cache/findmany/kube/pod/label/value:
    post:
      operationId: list_cached_kube_pod_label_value
      description: 获取缓存的Pod的标签键对应的值列表
      tags:
        - job
        - kube
      responses:
        default:
          description: ''
      x-bk-apigateway-resource:
        isPublic: false
        allowApplyPermission: false
        matchSubpath: false
        backend:
          type: HTTP
          method: post
          path: /api/v3/cache/findmany/kube/pod/label/value
          matchSubpath: false
          timeout: 0
          upstreams: {}
          transformHeaders: {}
        authConfig:
          userVerifiedRequired: false
        disabledStages: []
        descriptionEn:
  /api/v3/updatemany/hosts/all/property:
    put:
      operationId: batch_update_host_all_properties
      description: 根据主机id和属性批量更新主机属性
      tags:
        - nodeman
        - host
      responses:
        default:
          description: ''
      x-bk-apigateway-resource:
        isPublic: false
        allowApplyPermission: false
        matchSubpath: false
        backend:
          type: HTTP
          method: put
          path: /api/v3/updatemany/hosts/all/property
          matchSubpath: false
          timeout: 0
          upstreams: { }
          transformHeaders: { }
        authConfig:
          userVerifiedRequired: false
        disabledStages: [ ]
        descriptionEn:
