<?php
/**************************************************web通用错误**************************************************/
$config['applicationid_validation_failure']             = (Object)array('Code'=>'0001', 'Info'=>'业务ID错误！');
$config['application_host_exsit']                         = (Object)array('Code'=>'0002', 'Info'=>'业务下有主机，请先转出！');
$config['default_application_failure']                   = (Object)array('Code'=>'0003', 'Info'=>'默认业务无法删除！');
$config['upload_file_error_failure']                      = (Object)array('Code'=>'0004', 'Info'=>'请提供类型为xls、xlsx、csv的文件！');
$config['maintainer_length_error']                        = (Object)array('Code'=>'0005', 'Info'=>'业务运维配置过多！');
$config['samename_application_exsit']                    = (Object)array('Code'=>'0006', 'Info'=>'同名的业务已经存在！');
$config['get_maintainers_fail']                           = (Object)array('Code'=>'0007', 'Info'=>'获取运维列表失败！');
$config['edit_application_fail']                          = (Object)array('Code'=>'0008', 'Info'=>'修改业务失败！');
$config['application_length_error']                      = (Object)array('Code'=>'0009', 'Info'=>'业务名长度错误！');
$config['application_delete_error']                      = (Object)array('Code'=>'0010', 'Info'=>'删除业务错误！');
$config['innerip_column_not_found_failure']             = (Object)array('Code'=>'0011', 'Info'=>'缺少"内网IP"列！');
$config['permission_validation_failure']                 = (Object)array('Code'=>'0012', 'Info'=>'权限验证失败！');
$config['access_not_allowed']                             = (Object)array('Code'=>'0013', 'Info'=>'您的开发商未经过许可，不允许向CMDB导入主机');
$config['lack_of_empty_module']                           = (Object)array('Code'=>'0015', 'Info'=>'缺少空闲机模块！');
$config['lack_of_empty_module']                           = (Object)array('Code'=>'0016', 'Info'=>'缺少空闲机模块！');
$config['auth_no_param_applicationid']                   = (Object)array('Code'=>'0017', 'Info'=>'缺少参数ApplicationID！');
$config['auth_no_permission']                             = (Object)array('Code'=>'0018', 'Info'=>'没有权限！');
$config['illegal_request']                                 = (Object)array('Code'=>'0019', 'Info'=>'非法的请求！');
$config['new_application_error']                          = (Object)array('Code'=>'1001', 'Info'=>'新增业务失败！');
$config['producterlist_length_error']                     = (Object)array('Code'=>'1002', 'Info'=>'产品人员配置过多！');
$config['setname_length_error']                           = (Object)array('Code'=>'2001', 'Info'=>'集群名长度非法！');
$config['setch_length_error']                             = (Object)array('Code'=>'2002', 'Info'=>'集群中文名称长度非法！');
$config['setservice_status_error']                        = (Object)array('Code'=>'2003', 'Info'=>'非法的服务状态！');
$config['new_set_error']                                   = (Object)array('Code'=>'2004', 'Info'=>'新建集群失败！');
$config['edit_set_error']                                  = (Object)array('Code'=>'2005', 'Info'=>'修改集群失败！');
$config['delete_set_error']                               = (Object)array('Code'=>'2006', 'Info'=>'删除集群失败！');
$config['set_exsit_host']                                 = (Object)array('Code'=>'2007', 'Info'=>'集群下有主机，请先转出！');
$config['same_set_exist']                                 = (Object)array('Code'=>'2008', 'Info'=>'重复的集群名！');
$config['list_set_not_default']                           = (Object)array('Code'=>'2009', 'Info'=>'查询集群错误！');
$config['clone_set_error']                                 = (Object)array('Code'=>'2010', 'Info'=>'克隆集群错误！');
$config['clone_set_name_error']                           = (Object)array('Code'=>'2011', 'Info'=>'以上集群克隆失败！');
$config['set_Openstatus_length_error']                   = (Object)array('Code'=>'2012', 'Info'=>'集群Openstatus长度非法！');
$config['module_length_error']                            = (Object)array('Code'=>'3001', 'Info'=>'非法的模块名称长度！');
$config['new_module_error']                               = (Object)array('Code'=>'3002', 'Info'=>'新建模块错误！');
$config['same_module_name']                               = (Object)array('Code'=>'3003', 'Info'=>'重复的模块名！');
$config['appid_or_setid_inneed']                         = (Object)array('Code'=>'3004', 'Info'=>'集群ID或者业务ID错误！');
$config['appid_or_moduleid_inneed']                      = (Object)array('Code'=>'3005', 'Info'=>'模块ID或者业务ID错误！');
$config['appid_or_moduleid_or_setid_inneed']           = (Object)array('Code'=>'3006', 'Info'=>'模块ID或者业务ID或者集群ID错误！');
$config['des_outof_length']                               = (Object)array('Code'=>'3007', 'Info'=>'描述超过长度!');
$config['module_exsit_host']                              = (Object)array('Code'=>'3008', 'Info'=>'模块下有主机，请先转出！');
$config['delete_module_fail']                             = (Object)array('Code'=>'3010', 'Info'=>'删除模块失败！');
$config['list_module_not_default']                       = (Object)array('Code'=>'3011', 'Info'=>'查询模块错误！');
$config['edit_module_error']                              = (Object)array('Code'=>'3012', 'Info'=>'编辑模块错误！');
$config['lack_of_process_id']                             = (Object)array('Code'=>'3013', 'Info'=>'缺少进程ID！');
$config['delete_process_failed']                          = (Object)array('Code'=>'3014', 'Info'=>'删除进程失败！');
$config['lack_of_process_name']                           = (Object)array('Code'=>'3015', 'Info'=>'缺少进程名称！');
$config['insert_process_failure']                         = (Object)array('Code'=>'3016', 'Info'=>'插入进程失败！');
$config['lack_of_process_name_or_process_id']           = (Object)array('Code'=>'3017', 'Info'=>'缺少进程名称或者进程ID');
$config['update_process_failure']                         = (Object)array('Code'=>'3018', 'Info'=>'更新进程失败！');
$config['lack_of_module_name_or_process_id']            = (Object)array('Code'=>'3019', 'Info'=>'缺少进程ID或者模块ID');
$config['add_process_and_module_relation_failed']      = (Object)array('Code'=>'3020', 'Info'=>'增加进程模块关系失败');
$config['resource_app_not_exist']                         = (Object)array('Code'=>'4001', 'Info'=>'资源池业务不存在！');
$config['table_header_field_beyond']                     = (Object)array('Code'=>'4002', 'Info'=>'表头字段的长度超出16字符！');
$config['table_header_order']                             = (Object)array('Code'=>'4003', 'Info'=>'必须包含内网IP！');
$config['app_not_exist']                                   = (Object)array('Code'=>'4004', 'Info'=>'业务不存在！');
$config['lack_of_application_id']                         = (Object)array('Code'=>'4005', 'Info'=>'缺少业务ID！');
$config['lack_of_module_id']                               = (Object)array('Code'=>'4006', 'Info'=>'缺少模块ID！');
$config['lack_of_host_id']                                 = (Object)array('Code'=>'4007', 'Info'=>'缺少主机ID！');
$config['app_no_host']                                      = (Object)array('Code'=>'4008', 'Info'=>'当前业务下没有主机！');
$config['no_default_app_cannot_delete_host']            = (Object)array('Code'=>'4009', 'Info'=>'非默认业务资源池内主机不能删除！');
$config['cannot_delete_host']                             = (Object)array('Code'=>'4009', 'Info'=>'不能删除非私有云机器！');
$config['delete_host_belong_to_other']                   = (Object)array('Code'=>'4009', 'Info'=>'删除的主机里包含非当前业务的主机！');
$config['lack_of_setid_or_moduleid']                      = (Object)array('Code'=>'4010', 'Info'=>'缺少默认的集群或者模块！');
$config['lack_of_application_id'] 						= (Object)array('Code'=>'4005', 'Info'=>'缺少业务ID！');
$config['lack_of_module_id'] 							= (Object)array('Code'=>'4006', 'Info'=>'缺少模块ID！');
$config['lack_of_host_id'] 							    = (Object)array('Code'=>'4007', 'Info'=>'缺少主机ID！');
$config['app_no_host']						   		    = (Object)array('Code'=>'4008', 'Info'=>'当前业务下没有主机！');
$config['no_default_app_cannot_delete_host']			= (Object)array('Code'=>'4009', 'Info'=>'非默认业务资源池内主机不能删除！');
$config['cannot_delete_host']							= (Object)array('Code'=>'4009', 'Info'=>'不能删除非私有云机器！');
$config['delete_host_belong_to_other']					= (Object)array('Code'=>'4009', 'Info'=>'删除的主机里包含非当前业务的主机！');

/**************************************************api通用错误**************************************************/
$config['api_applicationid_illegal']                      = (Object)array('code'=>'0001', 'msg'=>'ApplicationID Illegal', 'extmsg'=>'非法的业务id');
$config['api_noexist_app']                                 = (Object)array('code'=>'0002', 'msg'=>'no app', 'extmsg'=>'没有业务');
$config['api_uin_illagal']                                 = (Object)array('code'=>'0004', 'msg'=>'user name illegal', 'extmsg'=>'用户id非法');
$config['api_only_default_app']                           = (Object)array('code'=>'0005', 'msg'=>'only default app exsit', 'extmsg'=>'只有默认业务');
$config['api_only_right_app']                             = (Object)array('code'=>'0006', 'msg'=>'only right to app', 'extmsg'=>'没权利访问业务');
$config['api_noexist_host']                                = (Object)array('code'=>'0011', 'msg'=>'no host','extmsg'=>'没有主机');
$config['api_invalid_input_appid']                       = (Object)array('code'=>'0016', 'msg'=>'invalid input ApplicationID','extmsg'=>'业务id输入无效');
$config['api_invalid_input_ip']                          = (Object)array('code'=>'0020', 'msg'=>'invalid input ip','extmsg'=>'输入ip无效');
$config['api_invalid_dup_ip']                            = (Object)array('code'=>'0021', 'msg'=>'duplicate input ip','extmsg'=>'重复的内网IP');
$config['api_add_ip_fail']                               = (Object)array('code'=>'0022', 'msg'=>'add ip fail','extmsg'=>'新增主机失败');
$config['api_get_ip_fail']                               = (Object)array('code'=>'0023', 'msg'=>'get ip fail','extmsg'=>'获取主机失败');
$config['api_params_illegal']                               = (Object)array('code'=>'0024', 'msg'=>'params illegal','extmsg'=>'参数错误');
$config['api_noexist_set']                               = (Object)array('code'=>'0030', 'msg'=>'params illegal','extmsg'=>'集群不存在');
$config['api_invalid_dup_module']                         = (Object)array('code'=>'0031', 'msg'=>'params illegal','extmsg'=>'重复的模块名');
$config['api_invalid_module_name']                              = (Object)array('code'=>'0032', 'msg'=>'params illegal','extmsg'=>'模块名非法');