{{- if .Values.adminserver.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ template "bk-cmdb.adminserver" . }}"
  labels:
{{ include "bk-cmdb.labels" . | indent 4 }}
spec:
  ports:
    - port: 80
      targetPort: {{ .Values.adminserver.port }}
  selector:
{{ include "bk-cmdb.matchLabels" . | indent 4 }}
    component: adminserver
{{- end }}
