FROM ccr.ccs.tencentyun.com/bk.io/centos7-cmdb:base
ENV container docker
COPY cmdb_authserver /data/cmdb/cmdb_authserver
RUN mkdir /data/cmdb/cmdb_authserver/logs
RUN chmod +x /data/cmdb/cmdb_authserver/cmdb_authserver