FROM mirrors.tencent.com/tencentos/tencentos3-minimal
ENV container docker
COPY cmdb_operationserver /data/cmdb/cmdb_operationserver
RUN mkdir /data/cmdb/cmdb_operationserver/logs
RUN chmod +x /data/cmdb/cmdb_operationserver/cmdb_operationserver
#time zone setting
ENV TimeZone=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TimeZone /etc/localtime && echo $TimeZone > /etc/timezone

