{{- if .Values.eventserver.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ template "bk-cmdb.eventserver" . }}"
  labels:
{{ include "bk-cmdb.labels" . | indent 4 }}
spec:
  ports:
    - port: 80
      targetPort: {{ .Values.eventserver.port }}
  selector:
{{ include "bk-cmdb.matchLabels" . | indent 4 }}
    component: eventserver
{{- end }}
