FROM ccr.ccs.tencentyun.com/bk.io/centos7-cmdb:base
ENV container docker
COPY cmdb_taskserver  /data/cmdb/cmdb_taskserver
RUN mkdir /data/cmdb/cmdb_taskserver/logs
RUN chmod +x /data/cmdb/cmdb_taskserver/cmdb_taskserver

