{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: bk-cmdb
spec:
  endpoints:
    - port: http
      path: "/metrics"
      interval: {{ .Values.serviceMonitor.interval }}
      {{- if .Values.serviceMonitor.metricRelabelings }}
      metricRelabelings: {{- include "common.tplvalues.render" ( dict "value" .Values.serviceMonitor.metricRelabelings "context" $) | nindent 8 }}
      {{- end }}
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app.kubernetes.io/name: bk-cmdb
{{- end }}
