FROM ccr.ccs.tencentyun.com/bk.io/centos7-cmdb:base
ENV container docker
COPY cmdb_syncserver /data/cmdb/cmdb_syncserver
RUN mkdir /data/cmdb/cmdb_syncserver/logs
RUN chmod +x /data/cmdb/cmdb_syncserver/cmdb_syncserver
#time zone setting
ENV TimeZone=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TimeZone /etc/localtime && echo $TimeZone > /etc/timezone

