{{- if .Values.coreservice.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ template "bk-cmdb.coreservice" . }}"
  labels:
{{ include "common.labels.standard" . | indent 4 }}
spec:
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.coreservice.port }}
  selector:
{{ include "common.labels.matchLabels" . | indent 4 }}
    component: coreservice
{{- end }}
