{{- if .Values.toposerver.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ template "bk-cmdb.toposerver" . }}"
  labels:
{{ include "bk-cmdb.labels" . | indent 4 }}
spec:
  ports:
    - port: 80
      targetPort: {{ .Values.toposerver.port }}
  selector:
{{ include "bk-cmdb.matchLabels" . | indent 4 }}
    component: toposerver
{{- end }}
