{{- if .Values.datacollection.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ template "bk-cmdb.datacollection" . }}"
  labels:
{{ include "common.labels.standard" . | indent 4 }}
spec:
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.datacollection.port }}
  selector:
{{ include "common.labels.matchLabels" . | indent 4 }}
    component: datacollection
{{- end }}
