FROM mirrors.tencent.com/tencentos/tencentos4-minimal
ENV container docker
COPY cmdb_datacollection /data/cmdb/cmdb_datacollection
RUN mkdir /data/cmdb/cmdb_datacollection/logs
RUN chmod +x /data/cmdb/cmdb_datacollection/cmdb_datacollection
#time zone setting
ENV TimeZone=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TimeZone /etc/localtime && echo $TimeZone > /etc/timezone

